### ISSUE TITLE
feature: add support of token based on RS algo

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-auth-jwt#1]

**Comment by njones** [comment]
I'd like to help push this forward. As of now you have the secret accessible via the config file or an env variable. Can we do the same for the RS Key and Cert (i.e. env vars "JWT_PRIV_KEY",  "JWT_PUB_KEY" and "JWT_KEY_ALGO" or "token_priv_key", "token_pub_key" and "token_key_algo")

Do you have any strong thoughts on this? around naming conventions? storage?

**Comment by greenpau** [comment]
> Do you have any strong thoughts on this? around naming conventions? storage?

@njones , I try not to be opinionated :-) haha :-) Please create a PR. Preliminary edits are.

* `token_key_algo` => `token_algo`
* `token_priv_key` => `token_private_key`
* `token_pub_key` => `token_public_key`
