### ISSUE TITLE
Consolidate Errors so that they can be used with errors.Is

### ISSUE THREAD

**Issue by njones** [greenpau/caddy-auth-jwt#10]
I would like to provide a pull request for changing errors from:

    return fmt.Errorf("user role is valid, but denied by default deny on empty access list")

to 

    var ErrEmptyAccessListDefaultDeny = fmt.Errorf("user role is valid, but denied by default deny on empty access list")

    return ErrEmptyAccessListDefaultDeny

Errors would be defined at the top of the file that they are first used in (in lexicographical file order if there are reused errors). This will allow the quick overview of what errors can be thrown and if they are used anywhere else in the code it will be more resistant to bugs (as a sentinel check with errors.Is won't be affected with any error corrections or clarifications).

Ideally I'd like to change it to:

    type strError string
    
    // allow error interface acceptance
    func (e strError) Error() string { return string(e) }
    
     const ErrEmptyAccessListDefaultDeny strError = "user role is valid, but denied by default deny on empty access list"

As this will provide a constant of the error that can't be changed.

This leaves out errors that provide more context with formatted variables like:

    return fmt.Errorf("failed to extract claims: %s", err)

This can be worked around with one additional type and an additional formatting method on the `strError` type.

    func (e strError) F(v ...interface{}) error { return fmtError{} }

So the formatted errors with context would look like

    const ErrExtractClaimsFailedError strError = "failed to extract claims: %w"

     return ErrExtractClaimsFailedError.F(err)

I have an example of using the formatting values with a constant error here: https://github.com/xa4b/git/blob/master/cfghttp/error.go#L35 (defined) https://github.com/xa4b/git/blob/master/cfghttp/wrapper.go#L450 (usage)

I'm opening an issue before submitting a PR to invite any discussion.

**Comment by greenpau** [comment]
> I'm opening an issue before submitting a PR to invite any discussion.

@njones , thank you for opening this issue! Generally, the above approach works well when there `switch`/`case` type of logic related to error handling. AWS SDK has a lot of that. This code base does not have much of it.

What is the benefit of implementing this?

**Comment by greenpau** [comment]
> Errors would be defined at the top of the file that they are first used in (in lexicographical file order if there are reused errors). This will allow the quick overview of what errors can be thrown and if they are used anywhere else in the code it will be more resistant to bugs (as a sentinel check with errors.Is won't be affected with any error corrections or clarifications).

@njones, with `fmt.Errorf` the code is readable. I am not sure that would be the case with the `errors.go` type of a file.

**Comment by njones** [comment]
> What is the benefit of implementing this?

I think that since errors are values in go it's expected that you can act on them (regardless of whether it's in a switch/case statement), so errors not just pass them along for logging purposes. Creating a variable or constant will also allow development with the `error.Is` method easy.

As a side point using error constants can help with resource management, as you're using a runtime function to display an error each time one occurs, whereas a constant is created at compile time. This is not significant, but as more modules are added efficiency does start to matter in aggregate.

> @njones, with fmt.Errorf the code is readable. I am not sure that would be the case with the errors.go type of a file.

I'm not sure if that's really a problem, as you'll still be able to have the same error message, just at the error point in code you'd have a more concise/fungible representation of the error. 

It could actually increase error visibility while browsing docs, because you will have the opportunity see them under a constant/variable heading in the docs. Where as inline errors would only be seen if browsing the code directly. I like to think seeing errors in the docs gives a nice understanding/overview of the error states that the code can get into, which I think can help with overall understanding of the code base.
