### ISSUE TITLE
The "token_sources" key is not restricting the token sources

### ISSUE THREAD

**Issue by njones** [greenpau/caddy-auth-jwt#13]
https://github.com/greenpau/caddy-auth-jwt/blob/master/pool.go#L112

Is where the check that a valid list of allowed sources exists... where here is where they are checked:

https://github.com/greenpau/caddy-auth-jwt/blob/master/validator.go#L83

And that checks every source. 

Also the current code does not check a custom token name from "token_name"?

I can submit a pull request for these changes, however I do have a few questions:

1. If you supply a custom token name, should that Append to the default token_names that can be used, or should it override and set the token name (so you can't use the defaults if you set a custom token name)?
2. When checking for the source of a token should the order be preserved by they way they are in the slice? or should it always check in a pre-determined order?
3. The Headers, Cookies, Parameters and Sources maps all are `map[string]bool`. Do you have any issue changing this to `map[string]struct{}` to show that the map is only used for quickly checking if a key exists and nothing more? I understand that the memory/GC/speed savings of making this change are minimal. I was thinking more of developers understanding how the code works.

**Comment by greenpau** [comment]
@njones , thank you for the questions! I think it is worth creating PR for `README.md`. I like your questions a lot!

> If you supply a custom token name, should that Append to the default token_names that can be used, or should it override and set the token name (so you can't use the defaults if you set a custom token name)?

@njones , override and set the token name.

> When checking for the source of a token should the order be preserved by they way they are in the slice? or should it always check in a pre-determined order?

@njones , the order be preserved by they way they are in the slice.

> The Headers, Cookies, Parameters and Sources maps all are map[string]bool. Do you have any issue changing this to map[string]struct{} to show that the map is only used for quickly checking if a key exists and nothing more? I

@njones , awesome suggestion!
