### ISSUE TITLE
xcaddy master build failing with caddy-auth-jwt

### ISSUE THREAD

**Issue by cameronelliott** [greenpau/caddy-auth-jwt#16]
This may not be of much interest here, but I thought I'd share in case someone knows.

This works okay: $ xcaddy build --with github.com/greenpau/caddy-auth-jwt

This works okay: $ xcaddy build master

**This fails: $ xcaddy build --with github.com/greenpau/caddy-auth-jwt master**

with:
```Temporary folder: /tmp/buildenv_2020-07-28-1502.465268976
Writing main module: /tmp/buildenv_2020-07-28-1502.465268976/main.go
Initializing Go module
exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
go: creating new go.mod: module caddy
Pinning versions
exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@master 
go: github.com/caddyserver/caddy/v2 master => v2.1.2-0.20200720231738-2bc30bb780f3
exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/greenpau/caddy-auth-jwt 
go: github.com/greenpau/caddy-auth-jwt upgrade => v1.0.4
Build environment ready
Building Caddy
exec (timeout=0s): /usr/local/go/bin/go build -o /home/c/caddy-auth-jwt/caddy -ldflags -w -s -trimpath 
# github.com/smallstep/certificates/authority/provisioner
/home/c/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/jwk.go:155:24:
 **assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values**
/home/c/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/x5c.go:197:24:
 **assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values**
Cleaning up temporary folder: /tmp/buildenv_2020-07-28-1502.465268976
exit status 2
```

The issue is clearly the: **`assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values`**

From my exploring, it looks like an issue between the two repos:
`https://github.com/smallstep/certificates`
and
`https://github.com/smallstep/cli`

That's as far as I have got. I will share this also at smallstep, maybe they will have some insight.

**Comment by greenpau** [comment]
> go: github.com/caddyserver/caddy/v2 master => v2.1.2-0.20200720231738-2bc30bb780f3

@cameronelliott , what does v2.1.2 mean in this context? I don't see this in the list of tags: https://github.com/caddyserver/caddy/tags

Also, I went to https://caddyserver.com/download and selected `caddy-auth-jwt` and it compiled no issues. 

I do not recognize these x509util ... perhaps the error comes from caddyserver itself.

**Comment by cameronelliott** [comment]
@greenpau Thank you for looking at this.

> @cameronelliott , what does v2.1.2 mean in this context? I don't see this in the list of tags: 

This is somehow a tag against the current master, the last tag is 2.1.1, which is 28 days old.
I am trying to get changes made much more recent to the caddy master. I presume 2.1.2 is a tag on the git master repo somehow, rather than a github published tag.

I suppose my key question, would be does this work for you:

From an empty dir:
**`$ xcaddy build master --with github.com/greenpau/caddy-auth-jwt`**

I suspect it will fail.
Here is the interesting part, this should succeed:
**`$ xcaddy build master`**

So, the master builds without `caddy-auth-jwt`, but will not build when `caddy-auth-jwt` is added.
This doesn't implicate `caddy-auth-jwt`, but it is where I am stuck.

By the way! Oh! I love `caddy-auth-jwt`!!! Thank you for making it! A very nice piece of work!

x509util is part of `github.com/smallstep/cli`, and is invoked by `github.com/smallstep/certificates`

I think what is happening, is somehow adding by adding `caddy-auth-jwt` to the xcaddy build, the
versions of the two `smallstep` packages is being affected and causing an issue.
But, I am not sure, and I have limited go modules experience.


Cameron

**Comment by greenpau** [comment]
>  xcaddy build master

@cameronelliott , you are correct. It fails to build against the master. However, building against the master is not the way to go. It could be WIP by the caddyserver committers. Specifically ACME stuff.

Why can't you specify a version of caddy, e.g. `xcaddy build v2.1.1`?

```
$  xcaddy build v2.1.1 --with github.com/greenpau/caddy-auth-jwt
2020/07/28 20:42:42 [INFO] Temporary folder: /tmp/buildenv_2020-07-28-2042.581869774
2020/07/28 20:42:42 [INFO] Writing main module: /tmp/buildenv_2020-07-28-2042.581869774/main.go
2020/07/28 20:42:42 [INFO] Initializing Go module
2020/07/28 20:42:42 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy
go: creating new go.mod: module caddy
2020/07/28 20:42:42 [INFO] Pinning versions
2020/07/28 20:42:42 [INFO] exec (timeout=5m0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.1.1
2020/07/28 20:42:43 [INFO] exec (timeout=5m0s): /usr/local/go/bin/go get -d -v github.com/greenpau/caddy-auth-jwt
go: github.com/greenpau/caddy-auth-jwt upgrade => v1.0.4
2020/07/28 20:42:43 [INFO] Build environment ready
2020/07/28 20:42:43 [INFO] Building Caddy
2020/07/28 20:42:43 [INFO] exec (timeout=5m0s): /usr/local/go/bin/go build -o /home/greenpau/tmptest/caddy -ldflags -w -s -trimpath
2020/07/28 20:42:47 [INFO] Build complete: caddy
2020/07/28 20:42:47 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-07-28-2042.581869774

./caddy version
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
```

**Comment by greenpau** [comment]
> By the way! Oh! I love caddy-auth-jwt!!! Thank you for making it! A very nice piece of work!

@cameronelliott , thank you! @njones is doing great work too!

**Comment by cameronelliott** [comment]
Well, I was trying to run https with using localhost and Chrome, but per Matt Holt, a recent fix may be necessary to get that to work:
[matt comment](https://caddy.community/t/localhost-certificate-invalid-on-mac-os/9036/4?u=cameron_elliott)

But, I found a work around, so I think I am fine to just wait until 2.1.2 gets tagged and available through the natural process, at which point I would guess everything would just work with an `xcaddy build`

Thanks again, for the response, and the project!
