### ISSUE TITLE
feature: add support for striping JWT token from a request

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-auth-jwt#2]
The idea is that a subsequent handler would not see the token.

**Comment by greenpau** [comment]
closing. belongs to `caddy-auth-portal`.

**Comment by thatnerdjosh** [comment]
@greenpau I think this should still be an option of some sort, thoughts?

**Comment by greenpau** [comment]
> I think this should still be an option of some sort, thoughts?

@thatnerdjosh , it is better if someone else would create a plugin to strip headers. It is more of `rewrite` function, i.e. outside of this plugin.

**Comment by thatnerdjosh** [comment]
Agreed, sounds good
