### ISSUE TITLE
feature: jwt > auth_url should allow different host

### ISSUE THREAD

**Issue by MexHigh** [greenpau/caddy-auth-jwt#22]
If I try to set the `jwt > auth_url` directive to something like `https://auth.example.com`, I get the following error: 

` Error during parsing: path directive must begin with '/'`

It should be possible to have the auth portal on another host so that hosts (e.g. `chat.example.com` and `videos.example.com`) use the same auth portal.

**Comment by greenpau** [comment]
@MexHigh , are you using `portal` or do you only use `jwt`?

**Comment by greenpau** [comment]
@MexHigh , release fix  https://github.com/greenpau/caddy-auth-jwt/releases/tag/v1.0.10

**Comment by MexHigh** [comment]
@greenpau Thanks :) I'm using both.

**Comment by greenpau** [comment]
@MexHigh , just out of curiosity ... please check whether it works for you now or now. `caddy-auth-portal` has previous release in `go.mod`. Idk whether it would matter or not.

**Comment by greenpau** [comment]
If it does not work and `go.mod` jwt version matters, then I will update `go.mod` in `portal` and push.

**Comment by MexHigh** [comment]
I'm getting an unused import error when trying to build caddy: `/go/pkg/mod/github.com/greenpau/caddy-auth-jwt@v1.0.10/caddyfile.go:21:2: imported and not used: "strings"`

**Comment by greenpau** [comment]
> I'm getting an unused import error when trying to build caddy: /go/pkg/mod/github.com/greenpau/caddy-auth-jwt@v1.0.10/caddyfile.go:21:2: imported and not used: "strings"

on it.

**Comment by MexHigh** [comment]
When I'm trying to build caddy with only `https://github.com/greenpau/caddy-auth-portal` it uses v1.0.9 of `jwt`. So you have to adjust the `go.mod` in `portal`.

**Comment by greenpau** [comment]
> When I'm trying to build caddy with only https://github.com/greenpau/caddy-auth-portal it uses v1.0.9 of jwt. So you have to adjust the go.mod in portal.

Will address it right now.

**Comment by greenpau** [comment]
@MexHigh , updated portal to v1.0.13! Please test that lucky number :-)

**Comment by MexHigh** [comment]
Does work now, thank you very much :)

**Comment by MexHigh** [comment]
Ok I did some more testing, and it actually does not work correctly yet. 

**Setup:** I'm using the `jwt` directive for let's say `chat.example.com` and the `auth_portal` on `auth.example.com`.

When I'm trying to access `chat.example.com` the access_token (which was issued by `auth.example.com`) is not sent (no `Cookie: access_token` request header). This causes a redirect back to `auth.example.com` where the token is accepted and I see the list of links again.

**Comment by greenpau** [comment]
> Ok I did some more testing, and it actually does not work correctly yet.
> is not sent (no Cookie: access_token request header).

@MexHigh , I am guessing it is related to the Cookie mode. `Secure; HttpOnly;`. See `SameSite` in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

Could you please share your Caddyfile? This will help a bit. 

Is `auth.example.com` running `caddy-auth-portal` or something else?

**Comment by MexHigh** [comment]
### My Caddyfile
```
{
    order jwt first
}


https://auth.example.com {

    route /jwt-auth-test {
        jwt {
              primary yes
              auth_url "https://auth.example.com"
              trusted_tokens {
                  static_secret {
                      token_name access_token
                      token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
                      token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
                  }
              }
              allow roles admin
        }
        respond "Login flow is working. You are authorized :)" 200
    }

    route {
        auth_portal {
            path /
            backends {
                local_backend {
                    type local
                    path /etc/caddy-auth/users.json
                    realm local
                }
            }
            jwt {
                token_name access_token
                token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
                token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
            }
            ui {
                login_template "/etc/caddy-auth/login.template"
                portal_template "/etc/caddy-auth/portal.template"
                logo_url "<removed>"
                logo_description "<removed>"
                links {
                    "Testpage" /jwt-auth-test
                    "Chat" "https://chat.example.com"
                }
            }
        }
    }

}


https://chat.example.com {

    route {
        jwt {
            auth_url "https://auth.example.com"
            trusted_tokens {
                static_secret {
                    token_name access_token
                    token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
                    token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
                }
            }
            allow roles admin
        }
        reverse_proxy http://[::1]:8050 {
            header_down -Server
        }
    }

}
```

Caddy is built with `xcaddy` and both `github.com/greenpau/caddy-auth-jwt` and `github.com/greenpau/caddy-auth-portal`.

**Comment by greenpau** [comment]
@MexHigh , could you please post screenshot from https://jwt.io/ of the token you get. Just want to see roles, etc.

The authentication works, correct? 

The access to `/jwt-auth-test` works too?

The access to `https://chat.example.com` does not work?

**Comment by greenpau** [comment]
@MexHigh , this a good issue to read https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain. I think this belongs to `caddy-auth-portal` now.

I opened https://github.com/greenpau/caddy-auth-portal/issues/30 to add support for intra domain cookie handling.
