### ISSUE TITLE
bug: auth_url not inherited from primary instance

### ISSUE THREAD

**Issue by MexHigh** [greenpau/caddy-auth-jwt#23]
### Example Caddyfile
```
{
  order jwt first
}

https://something.example.com {

  jwt {
      primary yes
      auth_url https://auth.example.com
      trusted_tokens {
          static_secret {
              token_name access_token
              token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
              token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
          }
      }
      allow roles admin
  }

  respond "Login flow is working. You are authorized :)" 200

}


https://chat.example.com {

  jwt

}
```

The "short" `jwt` directive should inherit all configuration from the primary instance above, but instead, when accessing `https://chat.example.com`, I'm getting redirected to `https://chat.example.com/auth`.

When setting the `auth_url` again like
```
jwt {
    auth_url https://auth.example.com
}
```
it works fine. The allowed roles and `trusted_tokens` are inherited correctly and the tokens issued by `https://auth.example.com` are accepted.

**Comment by greenpau** [comment]
@MexHigh , thank you for reporting this! Will fix it today. The issue is that I am setting a default when parsing Caddyfile. I should not.

**Comment by greenpau** [comment]
@MexHigh , I will update `portal` plugin by EOD and you should be good to go.

**Comment by greenpau** [comment]
@MexHigh , release https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.0.15
please test

**Comment by MexHigh** [comment]
Works for me now. Thank you very much.

**Comment by greenpau** [comment]
@MexHigh , btw, with your pattern of usage, you might benefit from the following pattern. 

It is not documented and I need to re-implement it in `portal` (was lost in transition).

```
https://chat.example.com {
  jwt {
    auth_url https://auth.example.com/?redirect_url=https://chat.example.com
  }
}
```

 The `redirect_url` in URL query creates `AUTH_PORTAL_REDIRECT_URL`. Upon successful authentication, the portal clears the cookie and redirect a user to the page specified in AUTH_PORTAL_REDIRECT_URL.

**Comment by greenpau** [comment]
@MexHigh , will be re-releasing this feature next. Probably in a few days.

**Comment by MexHigh** [comment]
Sounds convenient. I will try it out tomorrow.

**Comment by greenpau** [comment]
> Sounds convenient. I will try it out tomorrow.

@MexHigh , will ping you when it is ready. I think it will b e EOW. https://github.com/greenpau/caddy-auth-portal/blob/fe6d6face4d78d8fe3c6b9a1fe6e01d88004cf55/README.md#auto-redirect-url

**Comment by greenpau** [comment]
> Sounds convenient. I will try it out tomorrow.

@MexHigh , please try it and see if it works for you.

**Comment by MexHigh** [comment]
> ```
> https://chat.example.com {
>   jwt {
>     auth_url https://auth.example.com/?redirect_url=https://chat.example.com
>   }
> }
> ```

This works for me. But I have two issues here:

1. How do I redirect back the complete path accessed on `chat.example.com`? E.g. when accessing `https://chat.example.org/admin`, then I'm gettting redirected back to `https://chat.example.org/admin`.
Using `auth_url https://auth.example.com/?redirect_url=https://chat.example.com{uri}` does not work either.

2. Would't it be more convenient to set a subdirective under the primary `jwt` instance like: 
```
jwt {
  primary yes
  auth_url https://auth.example.org
  redirect_back yes
  ...
}
```
so that the short `jwt` directive could be used without setting the `auth_url` every time?

**Comment by MexHigh** [comment]
Just saw, that there is an issue on that #25.

**Comment by greenpau** [comment]
> Just saw, that there is an issue on that #25.

@MexHigh , will implement something like that ... i think I will make it default to redirect back. Then, will have disabled_redirect_back keyword in the config.

**Comment by greenpau** [comment]
> Just saw, that there is an issue on that #25.

@MexHigh, please test the latest version. the auto-redirect will work automatically. https://github.com/greenpau/caddy-auth-jwt#auto-redirect-url

**Comment by MexHigh** [comment]
Works like a charm also with different paths in the URL. Thank you.
