### ISSUE TITLE
Allow access filtering by path/placeholders

### ISSUE THREAD

**Issue by psrcek** [greenpau/caddy-auth-jwt#24]
I would like to manage access to certain assets with JWT tokens. Currently as far as I can tell that isn't possible.
I've tried the following but it doesn't seem to work (note the `{path}` placeholder)

```Caddyfile
my.site {
        route /auth* {
                respond * "Unauthorized" 401
        }

        root /assets/* /path/to/assets

        route /assets/* {
                jwt {
                        primary yes
                        trusted_tokens {
                                static_secret {
                                        token_secret mysecret
                                        token_issuer myissuer
                                }
                        }
                        allow roles admin {path}
                }

                uri strip_prefix /assets
                file_server
        }

        route /admin/* {
                jwt {
                        allow roles admin
                }
                respond * "admin only route" 200
        }
}
```

my token looks like this:
```json
{
  "iss": "myissuer",
  "aud": "assets",
  "auth_time": 1599719956,
  "user_id": 112,
  "roles": ["112", "/assets/test.txt", "/test.txt", "test.txt"],
  "sub": "112",
  "iat": 1600323830,
  "exp": 1700327430
}
```

additionally, if i add the admin role into the token it works fine.

**Comment by greenpau** [comment]
@psrcek , thank you for the issue! Just to confirm my own understanding of the issue. You have some secret javascript that you want accessible by authenticated users. Correct? If so it is a quick fix.

**Comment by psrcek** [comment]
I have some things stored in /assets that i want to be accessible to only users with the correct id which my token will contain.
Think of it as personal files for each user.

This module only allows role filtering. I thought i could get around it by using the {path} placeholder in the allow roles directive and then giving the path in the token, but that doesn't work.

**Comment by psrcek** [comment]
To clarify: I would have to manually add a route for each file and then add token roles to all the users i want to have access to that file. If I have many constantly changing files that's not a viable solution because it requires reloading the caddy config constantly, but adding file paths to the token is viable because then the only things changing are the files and the token which i can easily do because my app server generates it.

**Comment by greenpau** [comment]
> This module only allows role filtering. I thought i could get around it by using the {path} placeholder in the allow roles directive and then giving the path in the token, but that doesn't work.

@psrcek , understood. I will submit a PR to allow the path filtering functionality.

What you are asking would probably change the allow statement in the following way. The `allow` with `{path}` would create `deny {path} roles *`.

```
        route /assets/* {
                jwt {
                        primary yes
                        trusted_tokens {
                                static_secret {
                                        token_secret mysecret
                                        token_issuer myissuer
                                }
                        }
                        allow {path} roles admin {path}
                        // implicit: deny {path} roles *
                }

                uri strip_prefix /assets
                file_server
        }
```

**Comment by psrcek** [comment]
I don't know why you'd make a PR if you're the author of this project or why you're specifying {path} twice in there but sure.

Also while you're at it it would be nice if you just allowed all [placeholders](https://caddyserver.com/docs/caddyfile/concepts#placeholders) instead of just path like all the other things in the caddyfile do.

**Comment by greenpau** [comment]
> Also while you're at it it would be nice if you just allowed all placeholders instead of just path like all the other things in the caddyfile do.

@psrcek , imagine you are reading `README.md` file for this project. Please provide the part that describes the functionality you would like to see. 

> Also while you're at it it would be nice if you just allowed all placeholders instead of just path like all the other things in the caddyfile do.

I see where the confusion is. I did not mean `{path}` as a Caddy concept.

```
allow <PATH> roles admin
// implicit: deny <PATH> roles * (any)
```

**Comment by psrcek** [comment]
> I see where the confusion is. I did not mean {path} as a Caddy concept.

I did.

> Please provide the part that describes the functionality you would like to see.

I would like to be able to use placeholders in the allow roles directive so that I can allow access based on token data.
assume I use the same caddyfile as the one in the OP.

With the following token I would be allowed access to `https://my.site/assets/image1.png` and `https://my.site/assets/image2.png` but denied access to any other files in `/assets`. Therefore I could create a token that only grants access to specific files to specific users.

```JSON
{
  "iss": "myissuer",
  "aud": "assets",
  "auth_time": 1599719956,
  "user_id": 112,
  "roles": ["/assets/image1.png", "/assets/image2.png"],
  "sub": "112",
  "iat": 1600323830,
  "exp": 1700327430
}
```

**Comment by psrcek** [comment]
The only line in question here is `allow roles admin {path}` where `{path}` is treated literally and not as a placeholder like it should be.

**Comment by greenpau** [comment]
> With the following token I would be allowed access to https://my.site/assets/image1.png and https://my.site/assets/image2.png but denied access to any other files in /assets.

@psrcek , I am in sync here.

> The only line in question here is allow roles admin {path} where {path} is treated literally and not as a placeholder like it should be.

That would not work for the plugin. The `path` would be state prior to the roles.

```
allow <PATH> roles admin
```


Per `  "roles": ["/assets/image1.png", "/assets/image2.png"],`, the `roles` should be actual user roles.

Are you saying you want to embed a new claim into the token and then allow and restrict based on that?

**Comment by psrcek** [comment]
I just want to be able to allow access to certain paths with some claim in the token. As far as I can see your module only reads the roles claim so that's where I thought putting that would be appropriate, but as I've said three times so far that does not work because your module does not evaluate placeholders and just treats them as literal strings.

**Comment by psrcek** [comment]
if I see correctly you're now allowing roles access to specific paths. BUT you're not reading those paths from the token. That's great but still doesn't work for my use case. I need to be able to issue path specific tokens without specifying all the paths in the config separately. I've had to build a separate application to handle this now because of a company deadline but my use case still stands.

```Caddyfile
my.site {
        route /auth* {
                respond * "Unauthorized" 401
        }

        root /assets/* /path/to/assets

        route /assets/* {
                jwt {
                        primary yes
                        trusted_tokens {
                                static_secret {
                                        token_secret mysecret
                                        token_issuer myissuer
                                }
                        }
                        allow users to {token.paths}
                }

                uri strip_prefix /assets
                file_server
        }

        route /admin/* {
                jwt {
                        allow roles admin
                }
                respond * "admin only route" 200
        }
}
```

with the following token:

```json
{
  "iss": "myissuer",
  "aud": "assets",
  "auth_time": 1599719956,
  "user_id": 112,
  "roles": ["users", "112"],
  "paths": ["/assets/112/personalfile.txt"],
  "sub": "112",
  "iat": 1600323830,
  "exp": 1700327430
}
```

A user that has that token would have access to the "/assets/112/personalfile.txt" file, but nobody else would. Wildcard paths would also be greatly appreciated so that I can allow the user access to all of their files not just that specific one.

**Comment by greenpau** [comment]
> if I see correctly you're now allowing roles access to specific paths. BUT you're not reading those paths from the token.

@psrcek , I reopened this issue. I found a similar type of authorization here: https://developer.nexmo.com/conversation/guides/jwt-acl . Let's call it "Path-Based ACL".

As you can see, there is no groups, group, roles, role claims. The things one can access is all described inside the token.

```
{
  "iat": 1532093588,
  "jti": "705b6f50-8c21-11e8-9bcb-595326422d60",
  "sub": "jamie",
  "exp": "1532179987",
  "acl": {
    "paths": {
      "/*/users/**": {},
      "/*/conversations/**": {},
      "/*/sessions/**": {},
      "/*/devices/**": {},
      "/*/image/**": {},
      "/*/media/**": {},
      "/*/applications/**": {},
      "/*/push/**": {},
      "/*/knocking/**": {}
    }
  },
  "application_id": "aaaaaaaa-bbbb-cccc-dddd-0123456789ab"
}
```

Is this what you want? or you want to combine RBAC ACLs withe Path-Based  ACLs?

**Comment by greenpau** [comment]
@psrcek , please see https://github.com/greenpau/caddy-auth-jwt#path-based-access-lists for details.

**Comment by psrcek** [comment]
That is way better than it was before! Thank you for the amazing work implementing my request, and thanks for making such a great plugin :heart:
I think that this should work now for my case:

```json
{
  ...
  "acl": {
    "paths": [
      "/assets/112/**"
    ]
  },
  ...
}
```

with the following in my caddyfile:

```caddyfile
jwt {
   validate acl_path
}
```

I'll test it tomorrow. :wink: 

Though the readme is not very clear about which claims the module reads (is it configurable? Does it check all the claims?)

I'm assuming it only checks `token["acl"]["paths"]` and it has to be an array of strings, which is not always desirable - what if you wanted to exclude a specific subpath but allow everything else?

Maybe a better solution is to allow users to specify regexes in the token for what to allow like this:

```json
{
  ...
  "acl": {
    "pathregex": "^\/assets\/112(?!\/sys)(?:\/[A-Za-z0-9_.~-]+)+\/?.*$"
  },
  ...
}
```

That would allow really complex behavior, in this case denying access to the path `/assets/112/sys/**/*` but allowing access to anything else matching `/assets/112/**/*`. Just a thought seeing you're using regexes already, it shouldn't be that hard to modify it to use custom ones. :smile:

Oh and another thing, if I'm reading your code correctly, the path can't contain a # or a ? which would make query parameters and such unusable.

**Comment by greenpau** [comment]
> Though the readme is not very clear about which claims the module reads (is it configurable? Does it check all the claims?)

the `"acl": {"paths": [...] ...` and `"paths": [...]` is identical. It is the same as with `roles`, i.e. `groups`, `group`, `roles`, `roles` - all translates to `Roles`.

> I'm assuming it only checks token["acl"]["paths"] and it has to be an array of strings, 

It also checks `"paths": [...]`

> which is not always desirable - what if you wanted to exclude a specific subpath but allow everything else?

You would use separate `route` statements for that. This module is not a swiss knife :-)

> That would allow really complex behavior, in this case denying access to the path /assets/112/sys/**/* but allowing access to anything else matching /assets/112/**/*. Just a thought seeing you're using regexes already, it shouldn't be that hard to modify it to use custom ones. 😄

The `**/*` is really `**`. The regexes are as follows:

https://github.com/greenpau/caddy-auth-jwt/blob/2fe24b6c57f52b7d9cd4e221ae5a1ce1116c0cbf/access_list.go#L252-L255

> Oh and another thing, if I'm reading your code correctly, the path can't contain a # or a ? which would make query parameters and such unusable.

There is no match on query parameters. There are the two things passed to a validator when `validate acl_path` is used.

https://github.com/greenpau/caddy-auth-jwt/blob/2fe24b6c57f52b7d9cd4e221ae5a1ce1116c0cbf/plugin.go#L120-L121

@psrcek , enjoy!
