### ISSUE TITLE
feature request: redirect to page user was on

### ISSUE THREAD

**Issue by rayjlinden** [greenpau/caddy-auth-jwt#25]
Using auth_url one can redirect to a specific page:
```
auth_url https://auth.example.com/auth?redirect_url=auto
```

However, folks will "deep link" into my site and redirecting them to the home page or something after auth will be a very broken experience.

It is critical to have an option to redirect back to the url they were trying to get to before being redirected to auth:
Something like a special mode like this:
```
auth_url https://auth.example.com/auth?redirect_url={current_url}
```

**Comment by joe-getcouragenow** [comment]
Also critical for me too.
