### ISSUE TITLE
bug: logout button in portal does not work

### ISSUE THREAD

**Issue by MexHigh** [greenpau/caddy-auth-jwt#28]
When clicking the logout button at `/auth/portal`, I'm getting a 302 redirect back to `/auth/portal` with `/auth?logout=true` as initiator. **The access token is still present and valid after that.**

I think this is because `/auth` redirects back to `/auth/portal` when there is a valid token present, regardless of the `?logout=true` parameter.

![jwt](https://user-images.githubusercontent.com/50419884/93720562-24391200-fb8a-11ea-80cd-2acafd87d647.png)
_(just blacked out some private urls)_

**Comment by greenpau** [comment]
> I think this is because /auth redirects back to /auth/portal when there is a valid token present, regardless of the ?logout=true parameter.

@MexHigh , this is a but ... The logout url is "/auth/logout". Previously, I had it `?logout=true`.

Are you using the latest template? 

https://github.com/greenpau/caddy-auth-portal/blob/main/assets/templates/forms_portal.template

By the way, did you create your own template or do you use default?

**Comment by greenpau** [comment]
> By the way, did you create your own template or do you use default?

By default I mean "not specifying template at all". This way it pick one up from memory.

**Comment by MexHigh** [comment]
I'm using a slightly modified version of yours. But it may be some versions behind. I'm trying again with newer ones.

**Comment by MexHigh** [comment]
![jwt](https://user-images.githubusercontent.com/50419884/93721231-b6dbb000-fb8e-11ea-9993-0818f9a28656.png)

Token is still valid. I'm just getting a drifferent redirect chain. Haven't set the template at all in the `ui` subdirective.

**Comment by greenpau** [comment]
> Token is still valid. 

@MexHigh, do you still have `access_token` in your cookies? or do you expect the invalidation of the token previously granted to you?

**Comment by MexHigh** [comment]
I actually have two cookies named `access_token`, one with the correct JWT value and one with `delete` as content after logging out.
I expect that the logout removes the `access_token` cookie so that I need to re-authenticate when accessing a ressource secured with `jwt`.
![jwt](https://user-images.githubusercontent.com/50419884/93721738-43d43880-fb92-11ea-9ae8-d96473241dc0.png)

**Comment by greenpau** [comment]
@MexHigh , I suspect it is because the delete cookie parameters do not match ... I need to refactor the delete.

Could you please show all the fields of the two "access_token"? I think due to the use of domain, they do not clear out.

Will fix that shortly.

**Comment by greenpau** [comment]
@MexHigh , I still need to see the values ... have you tried to clear the tokens completely? Are you using firefox?

**Comment by greenpau** [comment]
@MexHigh , I am pretty sure that the delete token does not have domain included.

**Comment by MexHigh** [comment]
I'm using Chrome, because Firefox does not display the delete tokens I'm seeing in Chrome. But I tried both browsers, even the mobile versions of them. I'm using a fresh browser instances every time when testing this (setting a new temporary data directory for chrome using the `--user-data-dir` flag). I've tried deleting cookies by hand as well.

> @MexHigh , I am pretty sure that the delete token does not have domain included.

Chrome displays `.example.com` on the cookie containing the JWT and `example.com` (note the missing dot in front) on the delete cookie. So maybe Chrome just displays the affiliation of the cookie.

In Firefox, I don't see any change on the cookies when pressing the logout button.

After clicking the logout button and then accessing a different ressource secured with `jwt`, I'm only seeing the `access_token` with the correct JWT value.

**Comment by MexHigh** [comment]
I just discovered that the delete token expires at January 1st, 1970. Maybe this could be a problem.

![jwt](https://user-images.githubusercontent.com/50419884/93742872-2d0fff00-fbef-11ea-8de6-2d071d6480b6.png)

**Comment by greenpau** [comment]
@MexHigh , I just pushed `v1.1.1` https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.1.1

When specifying `cookie_domain`, please put a leading dot ,

```
cookie_domain .example.com
```

**Comment by greenpau** [comment]
additional reference: https://stackoverflow.com/questions/9618217/what-does-the-dot-prefix-in-the-cookie-domain-mean#:~:text=The%20leading%20dot%20means%20that,implementing%20the%20deprecated%20RFC%202109.

**Comment by MexHigh** [comment]
Works perfecty now. Even without the leading dot. Thank you.

**Comment by greenpau** [comment]
> Works perfecty now. Even without the leading dot. Thank you.

@MexHigh , thank you for testing! 👍 

On a separate note, I am planning adding MFA with App/Yubikey/Hardware tokens.

 https://github.com/greenpau/caddy-auth-portal#add-mfa-authenticator-application

Would you be interested in testing this feature?

**Comment by MexHigh** [comment]
> Would you be interested in testing this feature?

Yes, of course. Sounds good.
