### ISSUE TITLE
feature: authenticate tokens passed via Authorization (Bearer) header

### ISSUE THREAD

**Issue by tad-lispy** [greenpau/caddy-auth-jwt#31]
First of all thank you for sharing this plugin with us.

I am trying to use it in my application but I'm having trouble setting it up. Probably I'm doing something wrong.

Here is my Caddyfile :

```caddyfile
{
    debug
}


:3000 {

    route /restricted/* {
        jwt {
            primary yes
            trusted_tokens {
                static_secret {
                    token_secret I93HxiR7ISpoSKdlCOsGr1vvxvm1cSgycWTVw2rDOwGX03bcofUJybx3hxp7cCt2HPn46ZHvI5iSV4DSdO7spEsFS9tcwJUrWp5jTPgXFtPV4WWY2oP0ZIlPBfv3sEF9
                }
            }
            auth_url /login
            allow roles teacher
        }

        respond "Ok"
    }
}
```
I don't use this secret in production 😉

Here is the token:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGVhY2hlciIsInRlYWNoZXIiOiIzNDYyMDYzNC1lYzU1LTQ1NDctODRjZS04MTQ4MDE4NDZmN2QiLCJleHAiOjE2MDE0NjQxNjJ9.0xw9ASQoLrnIg5dXGRuPm4xGW857bOc2hOKmxno6rPc
```

decoded:

```
{
  "alg": "HS256",
  "typ": "JWT"
}
{
  "role": "teacher",
  "teacher": "a0b02cb7-48cb-402c-86c3-91579d8f5bd8",
  "exp": 1601459643
}
```

It works when I make a request like this:

```
$ http \
  --print="hbHB" \
  :3000/restricted  \
  "access_token==eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGVhY2hlciIsInRlYWNoZXIiOiIzNDYyMDYzNC1lYzU1LTQ1NDctODRjZS04MTQ4MDE4NDZmN2QiLCJleHAiOjE2MDE0NjQxNjJ9.0xw9ASQoLrnIg5dXGRuPm4xGW857bOc2hOKmxno6rPc" \

GET /restricted?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGVhY2hlciIsInRlYWNoZXIiOiIzNDYyMDYzNC1lYzU1LTQ1NDctODRjZS04MTQ4MDE4NDZmN2QiLCJleHAiOjE2MDE0NjQxNjJ9.0xw9ASQoLrnIg5dXGRuPm4xGW857bOc2hOKmxno6rPc HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/2.2.0



HTTP/1.1 200 OK
Content-Length: 2
Date: Tue, 29 Sep 2020 13:05:02 GMT
Server: Caddy

Ok
```

but my client is passing the token in the Authorization header, like this:

```
http \
    --print="hbHB" \
    :3000/restricted \
    "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGVhY2hlciIsInRlYWNoZXIiOiIzNDYyMDYzNC1lYzU1LTQ1NDctODRjZS04MTQ4MDE4NDZmN2QiLCJleHAiOjE2MDE0NjQxNjJ9.0xw9ASQoLrnIg5dXGRuPm4xGW857bOc2hOKmxno6rPc" \

GET /restricted HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGVhY2hlciIsInRlYWNoZXIiOiIzNDYyMDYzNC1lYzU1LTQ1NDctODRjZS04MTQ4MDE4NDZmN2QiLCJleHAiOjE2MDE0NjQxNjJ9.0xw9ASQoLrnIg5dXGRuPm4xGW857bOc2hOKmxno6rPc
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/2.2.0



HTTP/1.1 302 Found
Content-Length: 17
Content-Type: text/plain; charset=utf-8
Date: Tue, 29 Sep 2020 13:11:15 GMT
Location: /login?redirect_url=http://localhost:3000/restricted
Server: Caddy
Set-Cookie: access_token=delete; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: jwt_access_token=delete; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT

Unauthorized User
```

As you can see this doesn't work. Following logs are emitted by Caddy:

```
{"level":"debug","ts":1601387403.9026456,"logger":"http.authentication.providers.jwt","msg":"token validation error","error":"user invalid"}
{"level":"debug","ts":1601387403.9028213,"logger":"http.stdlib","msg":"http: superfluous response.WriteHeader call from github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP (server.go:247)"}
```

What should I do?

**Comment by greenpau** [comment]
> What should I do?

@tad-lispy , will help you out! First, what version of the plugin do you use? Please run the following:

```
<CADDY-BINARY> list-modules -versions | grep auth
```

**Comment by greenpau** [comment]
> but my client is passing the token in the Authorization header, like this:

@tad-lispy , what is that "client"?

I get what is going on ... once I get answers to the questions, I will let you know how to get it working. It is likely will require a patch on my side.

**Comment by tad-lispy** [comment]
Hey, you are fast 👍 

```
$ caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.2.0
http.authentication.hashes.scrypt v2.2.0
http.authentication.providers.http_basic v2.2.0
http.authentication.providers.jwt v1.0.17
http.handlers.authentication v2.2.0
```

The client is my web application written in Elm, so I could (and will if I have to) change it to use the query parameter. But it won't be convenient because:

1. There are other services that are using the same auth mechanism (in fact Caddy is a reverse proxy for them)
2. This particular endpoint is a reverse proxy for a 3rd party server and I don't want to send them my tokens. But there might be more query parameters, so I would have to filter them.

**Comment by greenpau** [comment]
> The client is my web application written in Elm, so I could (and will if I have to) change it to use the query parameter.

@tad-lispy , I will add a feature to force authentication without specifying "access_token" or "jwt_token"

**Comment by greenpau** [comment]
@tad-lispy , will find some time to do it today.

**Comment by tad-lispy** [comment]
Awesome, thanks!

**Comment by greenpau** [comment]
@tad-lispy , please use https://github.com/greenpau/caddy-auth-jwt/releases/tag/v1.0.18

Here is the option that enables the inspection of "Bearer":

```
    jwt {
      option validate_bearer_header
    }
```

Test it with:

```
curl --insecure -H "Authorization: Bearer JWT_TOKEN" -v https://localhost:8443/myapp
```

**Comment by tad-lispy** [comment]
Works! Thank you very much and have a nice day.

**Comment by simon-temple** [comment]
I was wondering... is there a way to configure validation via header OR query parameter?
I have a bunch of old clients and some use access_token parameter and others use Authorization headers?

Thanks

**Comment by greenpau** [comment]
@simon-temple , please open a separate issue and describe your use cases there. Will help you out 😃 and it is doable.

**Comment by greenpau** [comment]
@tad-lispy , @simon-temple , also, please support this project and [caddy-auth-portal](https://github.com/greenpau/caddy-auth-portal) by giving it a ⭐ and promoting it on the social media platforms you use!
