### ISSUE TITLE
documentation about RS tokens

### ISSUE THREAD

**Issue by zoutepopcorn** [greenpau/caddy-auth-jwt#34]
issue https://github.com/greenpau/caddy-auth-jwt/issues/1 is about implementing RS algo. In the Readme I see:
```
token_types: HS and RS algos are supported at the moment
```
In source code:
https://github.com/greenpau/caddy-auth-jwt/blob/dab79b5570ba9b53a6d8564f494d987a7e2169bb/caddyfile.go#L50-L71

I try to make an example working, but I cant get it working to post a valid Caddyfile.... Is it possible to provide some info about it in the Readme. 

Also wondering about this security issue on https://github.com/BTBurke/caddy-jwt:

When you run multiple sites from one Caddyfile, you can specify the location of a file that contains your PEM-encoded public key or your HMAC secret. Once again, you cannot use both for the same site because it would cause a security hole. However, you can use different methods on different sites because the configurations are independent.

**Comment by greenpau** [comment]
@njones , could you please help with the documentation?

**Comment by greenpau** [comment]
@zoutepopcorn , what is the header of JWT token that you get?

Did this work for you?

```
 //         rsa_file { 
 //           token_name <value> 
 //           token_rsa_file <path> 
 //           token_issuer <value> 
 //         } 
```

I don't think I implemented "kid"s in Caddyfile. That might now work.

**Comment by zoutepopcorn** [comment]
**header**
```json
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "EeG0GswlhYJk1DB5XimtKDEx6uNu7D517H3Xjw5EvDs"
}
```

**Error**
```
2020/10/13 16:19:30.997 DEBUG   http.authentication.providers.jwt       token validation error  {"error": "[the kid specified in the header was not found]"}
2020/10/13 18:19:30 [ERROR] Authenticating with jwt: [the kid specified in the header was not found]
```

**Comment by greenpau** [comment]
@zoutepopcorn , I need to put a fix for this.

I think the configuration should be something like this:

```
rsa_file { 
  token_name <value> 
  // token_rsa_file <kid> <path>
  token_rsa_file EeG0GswlhYJk1DB5XimtKDEx6uNu7D517H3Xjw5EvDs <path>
}
```

Do you use `portal` plugin with `jwt` or just `jwt`?

**Comment by zoutepopcorn** [comment]
> Do you use portal plugin with jwt or just jwt?

I use the jwt plugin. And Keycloak will create my tokens :D

I fiddled arround with config.json for caddy with token_rsa_dir and ENV settings nothing is working. My knowledge about go is nil, so sorry I'm not able to change it.. 

Your proposal for the Caddyfile
```
rsa_file { 
  token_name <value> 
  token_rsa_file <kid> <path>
}
```
Seems a perfect solution to me to include the kid.

**Comment by greenpau** [comment]
> I fiddled arround with config.json for caddy with token_rsa_dir and ENV settings nothing is working. My knowledge about go is nil, so sorry I'm not able to change it..

@zoutepopcorn , I will try finding some time this week to get this working for you. My other [plugin](https://github.com/greenpau/caddy-auth-portal) does not issue tokens with kids. I am going to add that functionality and then will make sure that this plugin's Caddyfile works too.

**Comment by greenpau** [comment]
@zoutepopcorn , I added the following documentation section. Hope it helps.

https://github.com/greenpau/caddy-auth-jwt#verification-with-rsa-public-keys

**Comment by zoutepopcorn** [comment]
Great it works with Keycloak, it can check de JWT's now in the correct way :+1: 

Thanks you very much.
