### ISSUE TITLE
feature: Development Dockerfile.dev

### ISSUE THREAD

**Issue by thatnerdjosh** [greenpau/caddy-auth-jwt#37]
To make local development easier working on different systems (with potentially varying versions of caddy, xcaddy, etc) It would be nice to have a `Dockerfile.dev` in order to have a common image people could work off of for contributions if they'd like.

If this is desired, I volunteer to create it.

**Comment by greenpau** [comment]
closing, see [here](https://github.com/greenpau/caddy-auth-jwt/pull/36#issuecomment-716564316)
