### ISSUE TITLE
query parameters not working on auth requests

### ISSUE THREAD

**Issue by jaedle** [greenpau/caddy-auth-jwt#38]
Hey!

I'm using `caddy-auth-jwt` to secure a combination of a SPA and a backing service. It works great, thanks for the great work!

It looks I've found an issue about the `redirect_uri`. I think the redirect uri is not url encoded which causes troubles when using query parameters.

Let's assume the following setup:
```
{
    admin off
    http_port 8000
    https_port 8443
}

(jwt_config) {
    token_name access_token
    token_secret very-secret
    token_issuer some-issuer
}

(trusted_tokens) {
    trusted_tokens {
        static_secret {
            import jwt_config
        }
    }
}

example.foo.bar {
    tls /certificates/example.pem /certificates/example.bar-key.pem
    
    route /* {
        jwt {
            primary yes
            import trusted_tokens
            auth_url /auth
            allow roles example
        }
        reverse_proxy http://ui:8080
    }

    route /auth* {
    	auth_portal {
    		path /auth
    		backends {
    			local_backend {
    				method local
    				path /users.json
    				realm local
    			}
    		}
    		jwt {
                         import jwt_config
    			token_lifetime 900
    		}
    	}
    }
}
```

When calling `https://example.foo.bar:8443/nested/route` I am redirected to`https://example.foo.bar:8443/auth?redirect_url=https://example.foo.bar:8443/nested/route`.

When calling `https://example.foo.bar:8443/?query=param` my redirect to `https://example.foo.bar:8443/auth?redirect_url=https://example.foo.bar:8443/?query=param` is causing an error (`404`)

When manually replacing the redirect_uri with an url-encoded `https://example.foo.bar:8443/auth&redirect_url=https%3A%2F%2Fexample.foo.bar%3A8443%2F%3Fquery%3Dparam` I am correctly being redirect to `https://example.foo.bar:8443/?query=param` after the login.

**Comment by greenpau** [comment]
@jaedle , you are missing “cookie_domain” directive. Please add. Also please move “auth” route up, i.e.  default/root should be after “auth” route”.

Please make these changes and retest.

**Comment by greenpau** [comment]
@jaedle , also please use the latest release.

**Comment by greenpau** [comment]
@jaedle , per your specific issue ... about query parameters is not being included, I may not be supported. Will check it later.

**Comment by greenpau** [comment]
@jaedle , I will add a configuration option to allow the passing of query parameters on redirect.

**Comment by jaedle** [comment]
> @jaedle , also please use the latest release.

Thanks for your feedback. I am using latest version and am Building my caddy binary through xcaddy.

I will try your changes and give you feedback, thanks!

**Comment by greenpau** [comment]
@jaedle , I doubt the redirect will work as you need it to. Will look at it this weekend.

**Comment by jaedle** [comment]
@greenpau when manually url encoding the redirect_uri everything works out amazingly fine.

I am using the query parameter from an external link to enter my SPA with a defined state.

**Comment by jaedle** [comment]
> @jaedle , I will add a configuration option to allow the passing of query parameters on redirect.

I think I was a little unclear on that, sorry.

I want to enter my single page application by clicking a link. This link is for example `https://example.foo.bar:8443/?query=param`.
I expect to be redirected to this url when the authentication is done, but when redirecting to the auth provider the url is not encoded and the request is broken.

**Comment by jaedle** [comment]
I've tried to create a minimal example to reproduce the problem.

https://github.com/jaedle/caddy-jwt-auth-redirect-example

The example provides an unprotected variant to show the expected behavior and the protected variant not working with redirects including query parameters.

if anything is unclear on this example, just give me a ping.

Thanks for digging into this! 👍

**Comment by greenpau** [comment]
@jaedle , the changes to get to what you need would be here. https://github.com/greenpau/caddy-auth-jwt/blob/bf42fe83ddf73472514298fa14d77b3a37432c5a/pkg/handlers/redirect.go#L36

I am on my mobile right now, will update this issue later.

**Comment by greenpau** [comment]
@jaedle , love the following shortcuts 👍 

```

(jwt_config) {
    token_name access_token
    token_secret very-secret
    token_issuer some-issuer
}

(trusted_tokens) {
    trusted_tokens {
        static_secret {
            import jwt_config
        }
    }
}
```

**Comment by greenpau** [comment]
Note to myself ... there is a difference between `url.QueryEscape` and `url.PathEscape`. I will be implementing `url.QueryEscape` and see how it performs.

**Comment by greenpau** [comment]
@jaedle , please test with `caddy-auth-jwt v1.1.9` and `caddy-auth-portal v1.2.18` and report back.

**Comment by jaedle** [comment]
Great work, thanks! 👍  🥳 

The. given [](https://github.com/jaedle/caddy-jwt-auth-redirect-example) works out perfectly fine.

This is where I plan to use this in production:
https://github.com/jaedle/vinotheque/blob/8d2f0a76f0117e93ee07474ca3754672b5128f82/e2e/show-wines.e2e.ts#L27

Thanks again!

**Comment by jaedle** [comment]
I hope you don't pick this one up as a critic:
I would have loved to write the fix myself but when checking out your repo running a `make all` was a huge mess. If i can send along a suggestion with my regards and thanks:

Maybe think about documenting the development process for external contributors a little bit better so they know what they have to do get up to speed for development 😄

**Comment by greenpau** [comment]
> I hope you don't pick this one up as a critic:

@jaedle , I hear you and it is all good feedback. I perform integration testing with the `portal`. I maintain `caddy-auth-jwt`, `caddy-auth-portal`, and `caddy-trace` under the same parent directory. That allows building code locally.

https://github.com/greenpau/caddy-auth-portal/blob/1b08b04f5b75796b2d6733caec862d84586e2b5f/Makefile#L18-L27
