### ISSUE TITLE
Issue with custom headers

### ISSUE THREAD

**Issue by kirsch33** [greenpau/caddy-auth-jwt#40]
Not sure what I'm doing wrong here, but I want to have token claim info available between each of the subdomains on my server. Below is my sanitized Caddyfile that has the relevant sections:
```
https://example.net {
        route /auth* {

                realip {
                       header "X-Forwarded-For"
                        from cloudflare
                        maxhops 5
                }

                encode gzip

                header {
                        header_up X-Forwarded-For {>CF-Connecting-IP}
                        Strict-Transport-Security max-age=31536000;
                        X-Content-Type-Options nosniff
                        X-Frame-Options DENY
                        Referrer-Policy no-referrer-when-downgrade
                        X-XSS-Protection 1
               }

                auth_portal {
                        path /auth
                                backends {
                                        local_backend {
                                                method local
                                                path /authdb/users.json
                                                realm local
                                                }
                                        }
                        cookie_domain example.net
                        jwt {
                                token_name access_token
                                token_secret TOKEN_SECRET
                                token_issuer TOKEN_ISSUER
                                token_lifetime 86400
                        }

                        ui {
                                links {
                                        "Subdomain" https://subdomain.example.net
					"Subdomain2" https://subdomain2.example.net
				}
			}
                }
        }

        route {
                realip {
                        header "X-Forwarded-For"
                        from cloudflare
                        maxhops 5
                }

                encode gzip

                header {
                        header_up X-Forwarded-For {>CF-Connecting-IP}
                        Strict-Transport-Security max-age=31536000;
                        X-Content-Type-Options nosniff
                        X-Frame-Options DENY
                        Referrer-Policy no-referrer-when-downgrade
                        X-XSS-Protection 1
                }
                redir https://example.net/auth 302
        }

        tls my_email {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        }

        log {
                format formatted
                output file /authdb/access.log {
                        roll_size 50MiB
                        roll_keep 5
                        roll_keep_for 48h
                        }
                }
}

https://subdomain.example.net {
        route {
        jwt {
                primary yes
                enable claim headers
                trusted_tokens {
                        static_secret {
                                token_name access_token
                                token_secret TOKEN_SECRET
                                token_issuer TOKEN_ISSUER
                                }
                        }
                auth_url https://example.net/auth?redirect_url=https://subdomain.example.net
                allow roles user
                allow roles superadmin
                }
        }
        tls my_email {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        }

        reverse_proxy 192.168.42.12:32400

        encode gzip

        header {
                request_header -Referer
                header_upstream X-Forwarded-For {>CF-Connecting-IP}
                Strict-Transport-Security max-age=31536000;
                X-Content-Type-Options nosniff
                X-Frame-Options DENY
                Referrer-Policy no-referrer-when-downgrade
                X-XSS-Protection 1
        }
}

https://subdomain2.example.net {

        route {
                jwt 
        }

        tls my_email {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        }

        reverse_proxy 192.168.42.12:9091

        encode gzip

        header {
                request_header -Referer
                header_upstream X-Forwarded-For {>CF-Connecting-IP}
                X-Token-Subject {userIdentity}
                Strict-Transport-Security max-age=31536000;
                X-Content-Type-Options nosniff
                X-Frame-Options DENY
                Referrer-Policy no-referrer-when-downgrade
                X-XSS-Protection 1
        }
}
```

As you can see, I first tried just adding "enable claim headers" to the primary jwt instance but that wasnt working, so I have been trying to manually add the X-Token-Subject header to subdomain2 but cant see to narrow down the syntax of the user_identity variable? Interestingly when I look at the logs for a request, the common_log format shows the correct username but im not sure what field that's referencing.

**Comment by greenpau** [comment]
@kirsch33 , let's do it one by one:

```
https://subdomain.example.net {
        route {
        jwt {
                primary yes
                enable claim headers
                trusted_tokens {
                        static_secret {
                                token_name access_token
                                token_secret TOKEN_SECRET
                                token_issuer TOKEN_ISSUER
                                }
                        }
                auth_url https://example.net/auth?redirect_url=https://subdomain.example.net
                allow roles user
                allow roles superadmin
                }
```

Here, you need to replace:

```
auth_url https://example.net/auth?redirect_url=https://subdomain.example.net
```
with:

```
auth_url https://example.net/auth
```

The plugin knows how to create the redirect.

**Comment by greenpau** [comment]
@kirsch33 , also, what kind of errors do you get?

**Comment by greenpau** [comment]
@kirsch33 , next ... the following needs to be rewritten as:

```
https://subdomain2.example.net {

        route {
                jwt 
        }

        tls my_email {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        }

        reverse_proxy 192.168.42.12:9091

        encode gzip

        header {
                request_header -Referer
                header_upstream X-Forwarded-For {>CF-Connecting-IP}
                X-Token-Subject {userIdentity}
                Strict-Transport-Security max-age=31536000;
                X-Content-Type-Options nosniff
                X-Frame-Options DENY
                Referrer-Policy no-referrer-when-downgrade
                X-XSS-Protection 1
        }
}
```
to:

```
https://subdomain2.example.net {
        encode gzip

        tls my_email {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        }

        header {
                request_header -Referer
                header_upstream X-Forwarded-For {>CF-Connecting-IP}
                X-Token-Subject {userIdentity}
                Strict-Transport-Security max-age=31536000;
                X-Content-Type-Options nosniff
                X-Frame-Options DENY
                Referrer-Policy no-referrer-when-downgrade
                X-XSS-Protection 1
        }

        route {
                jwt 
                reverse_proxy 192.168.42.12:9091
        }
}
```

**Comment by greenpau** [comment]
@kirsch33 , also, try removing `header` config. You need to go to a very basic config. Then, scale up. My concerns are `header` and `encoding`.

```
        header {
                request_header -Referer
                header_upstream X-Forwarded-For {>CF-Connecting-IP}
                X-Token-Subject {userIdentity}
                Strict-Transport-Security max-age=31536000;
                X-Content-Type-Options nosniff
                X-Frame-Options DENY
                Referrer-Policy no-referrer-when-downgrade
                X-XSS-Protection 1
        }
```

I think the reverse proxy needs to be inside a `route`, but I could be wrong.

**Comment by kirsch33** [comment]
Hey Paul, I have taken all of your advice including complete removal of the encoding and header sections to no avail. Here is my updated and sanitized Caddyfile:

```
https://example.net {

        tls MY_EMAIL {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        }

        route /auth* {
                realip {
                       header "X-Forwarded-For"
                        from cloudflare
                        maxhops 5
                }

                auth_portal {
                        path /auth
                                backends {
                                        local_backend {
                                                method local
                                                path /authdb/users.json
                                                realm local
                                                }
                                        }
                        cookie_domain example.net
                        jwt {
                                token_name access_token
                                token_secret TOKEN_SECRET
                                token_issuer TOKEN_ISSUER
                                token_lifetime 86400
                        }

                        ui {
                                links {
                                        "Subdomain1" https://subdomain1.example.net
                                        "Subdomain2" https://subdomain2.example.net
                                }
                        }
                }
        }

        route {
                realip {
                        header "X-Forwarded-For"
                        from cloudflare
                        maxhops 5
                }

                redir https://example.net/auth 302
        }

        log {
                format formatted
                output file /authdb/access.log {
                        roll_size 50MiB
                        roll_keep 5
                        roll_keep_for 48h
                }
        }
}

https://subdomain1.example.net {

        tls MY_EMAIL {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        }

        route {
                jwt {
                        primary yes
                        enable claim headers
                        trusted_tokens {
                                static_secret {
                                        token_name access_token
                                        token_secret TOKEN_SECRET
                                        token_issuer TOKEN_ISSUER
                                        }
                                }
                        auth_url https://example.net/auth
                        allow roles user
                        allow roles superadmin
                }

                reverse_proxy 192.168.42.12:32400
        }
}

https://subdomain2.example.net {                                                                                                                                                                 
                                                                                              
        tls MY_EMAIL {                                                                                         
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}                                                               
        }                                                                                                               
                                                                                                                                                                                                                              
        route {                                                                                                         
                jwt                                                                                                     
                                                                                                                        
                reverse_proxy 192.168.42.12:9091                                                                        
        }                                                                                                               
}                                                                                                                       
```

The above Caddyfile, in my case, returns a log resembling the following when accessing subdomain2.example.net:


`{"level":"info","ts":1606113558.8473835,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"CLOUDFLARE_IP","proto":"HTTP/1.1","method":"POST","host":"subdomain2.example.net","uri":"/subdomain2/rpc","headers":{"Sec-Fetch-Dest":["empty"],"Referer":["https://subdomain2.example.net/subdomain2/web/"],"Cf-Ray":["CF_RAY"],"Content-Length":["439"],"X-Requested-With":["XMLHttpRequest"],"Origin":["https://subdomain2.example.net"],"Sec-Fetch-Site":["same-origin"],"Sec-Fetch-Mode":["cors"],"Accept-Language":["en-US,en;q=0.9"],"Cookie":["__cfduid=CFDUID; access_token=ACCESS_TOKEN"],"X-Forwarded-Proto":["https"],"Accept":["application/json, text/javascript, */*; q=0.01"],"Cf-Request-Id":["CF_REQUEST_ID"],"Cdn-Loop":["cloudflare"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Cf-Connecting-Ip":["ACTUAL_IP"],"Connection":["Keep-Alive"],"Cf-Ipcountry":["US"],"X-Forwarded-For":["ACTUAL_IP"],"Content-Type":["json"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"],"Accept-Encoding":["gzip"]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"","proto_mutual":true,"server_name":"subdomain2.example.net"}},"common_log":"CLOUDFLARE_IP - MY_EMAIL [23/Nov/2020:06:39:18 +0000] \"POST /subdomain2/rpc HTTP/1.1\" 200 76","duration":0.002014479,"size":76,"status":200,"resp_headers":{"Content-Type":["application/json; charset=UTF-8"],"Date":["Mon, 23 Nov 2020 06:39:18 GMT"],"Content-Length":["76"],"Content-Encoding":["gzip"],"Server":["Caddy","Subdomain2"]}}   `

**Comment by kirsch33** [comment]
Also, I forgot to mention, as you can see it does manage to put MY_EMAIL in the common_log format of the log but thats the only place I see it--and regardless I'm not sure if thats the "enable claim headers" doing that or just default behavior considering I dont see any of the other headers such as "X-Token-Subject"

**Comment by greenpau** [comment]
@kirsch33 are you able to browse subdomain2.example.net? Are you able to get to reverse proxy or you are brought back to auth endpoint?

We will get to headers later... please add ‘caddy-trace’ plugin and insert it between jwt and reverse-proxy lines. In the output, you will see the headers being passed from jwt to reverse-proxy plugins.

https://github.com/greenpau/caddy-trace

Once you collect trace, please attach it here in a text file.

**Comment by kirsch33** [comment]
@greenpau yes i am able to access and use subdomain2.example.net after authenticating via the portal. I will add caddy-trace, rebuild and follow up shortly

**Comment by kirsch33** [comment]
@greenpau well, were getting somewhere. i added this line:

`trace tag="GWS" response_debug=yes`

which returned this log line:

`{"level":"debug","time":"2020-11-24T02:18:43.622Z","msg":"debugging request","request_id":"2036a77e-c748-4445-8108-b0fb61060643","direction":"incoming","tag":"GWS","method":"POST","proto":"HTTP/2.0","host":"subdomain2.example.net","uri":"/subdomain2/rpc","remote_addr_port":"CLOUDFLARE_IP","remote_addr":"CLOUDFLARE_IP","remote_port":CLOUDFLARE_PORT,"content_length":24,"cookie_count":2,"user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","referer":"https://subdomain2.example.net/subdomain2/web/","cookies":[{"Name":"__cfduid","Value":"CFDUID","Path":"","Domain":"","Expires":"0001-01-01T00:00:00Z","RawExpires":"","MaxAge":0,"Secure":false,"HttpOnly":false,"SameSite":0,"Raw":"","Unparsed":null},{"Name":"access_token","Value":"ACCESS_TOKEN","Path":"","Domain":"","Expires":"0001-01-01T00:00:00Z","RawExpires":"","MaxAge":0,"Secure":false,"HttpOnly":false,"SameSite":0,"Raw":"","Unparsed":null}],"query_params":{},"headers":{"Accept":"application/json, text/javascript, */*; q=0.01","Accept-Encoding":"gzip","Accept-Language":"en-US,en;q=0.9","Cdn-Loop":"cloudflare","Cf-Connecting-Ip":"ACTUAL_IP","Cf-Ipcountry":"US","Cf-Ray":"CF_RAY","Cf-Request-Id":"CF_REQUEST_ID","Cf-Visitor":"{\"scheme\":\"https\"}","Content-Length":"24","Content-Type":"json","Origin":"https://subdomain2.example.net","Referer":"https://subdomain2.example.net/subdomain2/web/","Sec-Fetch-Dest":"empty","Sec-Fetch-Mode":"cors","Sec-Fetch-Site":"same-origin","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","X-Forwarded-For":"ACTUAL_IP","X-Forwarded-Proto":"https","X-Requested-With":"XMLHttpRequest","X-Token-Subject":"akirsch","X-Token-User-Email":"MY_EMAIL","X-Token-User-Roles":"superadmin guest anonymous"},"form":{}}`

which obviously includes the correct headers. no the question is, how do I access these without trace? not sure what I'm doing to cause them to be 'hidden' otherwise

**Comment by greenpau** [comment]
@kirsch33 , now, what header key and values do you need to pass to reverse-proxy for your setup to work?

**Comment by greenpau** [comment]
> which obviously includes the correct headers. now the question is, how do I access these without trace? not sure what I'm doing to cause them to be 'hidden' otherwise

@kirsch33 , the headers you see with trace are exactly the same that are being password to the reverse proxy.

There was a similar issue [here](https://github.com/greenpau/caddy-auth-portal/issues/58#issuecomment-719130103).

The PHP backend got:

```
REMOTE_USER = bdda81e3-f768-4094-be09-e985955882fe
HTTP_X_TOKEN_SUBJECT = andrew
HTTP_X_TOKEN_USER_EMAIL = myemail@gmail.com
HTTP_X_TOKEN_USER_ROLES = superadmin guest anonymous
```

**Comment by kirsch33** [comment]
@greenpau for my current project I just need to be able to reference the current user username, so "X-Token-Subject"... but heres a related question. the documentation for caddy-auth-jwt says "the plugin passes the user identity identifier back to the Caddy server" meaning I could just set "user_identity subject" which should also make this info available, but I'm not sure how to get that working either?

Both would, for me, arrive at the same solution...just trying to make sure I understand everything going on

**Comment by greenpau** [comment]
@kirsch33 , I think I understood your problem... pls correct me if I am wrong.

❗  use `user_identity` Caddyfile directive.

Please read: https://github.com/greenpau/caddy-auth-jwt/blob/main/README.md#user-identity

---

> the documentation for caddy-auth-jwt says "the plugin passes the user identity identifier back to the Caddy server" meaning I could just set "user_identity subject" which should also make this info available, but I'm not sure how to get that working either?

@kirsch33 , upon successful authentication, the building of `userIdentity` starts

https://github.com/greenpau/caddy-auth-jwt/blob/4fe3ff57c5d73bc1f753ec477b38cbe37f99275f/pkg/auth/authorizer.go#L201-L251

At that moment, when `enable claim headers` is used, the header is being set.

https://github.com/greenpau/caddy-auth-jwt/blob/4fe3ff57c5d73bc1f753ec477b38cbe37f99275f/pkg/auth/authorizer.go#L245-L247

Finally, the previously set headers make its way to `UserIdentity.Metadata`:

https://github.com/greenpau/caddy-auth-jwt/blob/4fe3ff57c5d73bc1f753ec477b38cbe37f99275f/plugin.go#L73-L77

> the user identity identifier

Next, the **identifier** here is NOT Metadata, but rather ID. The ID is being generated by the plugin 

https://github.com/greenpau/caddy-auth-jwt/blob/4fe3ff57c5d73bc1f753ec477b38cbe37f99275f/plugin.go#L70-L72

The ID depends on the following calculation:

https://github.com/greenpau/caddy-auth-jwt/blob/4fe3ff57c5d73bc1f753ec477b38cbe37f99275f/pkg/auth/authorizer.go#L215-L225

If you want to set the identity, then use `user_identity` Caddyfile directive :-)

https://github.com/greenpau/caddy-auth-jwt/blob/b55aecc559b9b62fd0036be2494574a9893c8aa0/caddyfile.go#L280-L284

**Comment by greenpau** [comment]
@kirsch33 , it is great that you are asking these questions! 👍 This would help building a better `README.md` file.

**Comment by greenpau** [comment]
@kirsch33 , you could also create a PR and improve documentation yourself!

**Comment by kirsch33** [comment]
@greenpau  i appreciate that, because i feel like youre explaining things very well I just am so new to all of this it takes me a while to understand. once I get a grasp on things id love to help anyway I can!

its still not completely clear to me. `user_identity` is built regardless of if `enable claim headers` is specified, but is that in anyway accessible from local Caddyfile? as in, if I wanted to specify my own downstream header:
`header_down Custom-Username-Header {user_identity_variable_from_plugin}`

im asking this because even if _dont_ specify `enable claim headers` then I can see still my token email address in the common_log output...meaning its getting that info somehow?

completely separate from the question above, if i use `enable claim headers` why is it that i'm only able to see the token headers using the trace plugin? as in, standard info level caddy logs do not display them so I dont think my downstream services would be able to see them either.

**Comment by kirsch33** [comment]
@greenpau to expand on part 1 above...if I set `user_identity subject` inside `jwt {` for subdomain2, i can actually see the username (or subject) in the common_log section of a standard Caddy info level log line...which is why it seems like it seems like it should be accessible somehow from local Caddyfile (this is _without_ `enable claim headers`)

interestingly to get the behavior above you have to set `user_identity subject` inside subdomain2 `jwt {` ...if you place it in the primary jwt instance you get the token email instead for a subdomain2 log line.

**Comment by greenpau** [comment]
> interestingly to get the behavior above you have to set user_identity subject inside subdomain2 jwt { ...if you place it in the primary jwt instance you get the token email instead for a subdomain2 log line.

@kirsch33 , this looks like a bug ... non-primary instance issue

**Comment by greenpau** [comment]
> its still not completely clear to me. user_identity is built regardless of if enable claim headers is specified, but is that in anyway accessible from local Caddyfile? as in, if I wanted to specify my own downstream header:
header_down Custom-Username-Header {user_identity_variable_from_plugin}

@kirsch33 , idk the answer to this. This is a good question to ask in https://caddy.community

**Comment by greenpau** [comment]
@kirsch33 , to sum it up. The primary `jwt` instance config does not propagate to non-primary `jwt` instance with respect to `enable claim headers` Caddyfile directive.

As a workaround, please specify it in the non-primary `jwt` instance:

```
https://subdomain2.example.net {                                                                                                                                                                 
                                                                                              
        tls MY_EMAIL {                                                                                         
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}                                                               
        }                                                                                                               
                                                                                                                                                                                                                              
        route {                                                                                                         
                jwt {
                    enable claim headers
                }                                                                                                   
                                                                                                                        
                reverse_proxy 192.168.42.12:9091                                                                        
        }                                                                                                               
}      
```

Do you see the headers being passed after that change?

**Comment by kirsch33** [comment]
@greenpau i can confirm that after making that change i still only see the headers if I use the trace plugin. without trace (aka just normal caddy logs) do not show the headers.

**Comment by kirsch33** [comment]
@greenpau actually just figured out that if I set log levels to debug i can see the headers--even without trace

this can be closed at this point. thanks for hanging in there with me Paul.

**Comment by greenpau** [comment]
@kirsch33 , any time! Will keep it open until i have a chance looking into nonprimary instance issue.
