### ISSUE TITLE
ERROR: unrecognized directive: primary

### ISSUE THREAD

**Issue by averri** [greenpau/caddy-auth-jwt#41]
I have created a `Dockerfile` with this module as follows:

```Dockerfile
FROM caddy:2.2.1-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/greenpau/caddy-auth-jwt

FROM caddy:2.2.1

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

I have the following `Caddyfile`:
```text
:443 {
  tls /etc/caddy/fullchain.pem /etc/caddy/privkey.pem
}

jwt {
    primary yes
    trusted_tokens {
      static_secret {
        token_name jwt_token
        token_secret my_secret
        token_issuer localhost
      }
    }
    auth_url /login
    allow roles anonymous guest admin
}


auth.mydomain.com:443 {
    reverse_proxy  localhost:8080
}

secure.mydomain.com:443 {
  jwt
  reverse_proxy  localhost:7878
}
```

When starting the referred Docker container with the above Caddyfile I get the following error:

```
caddy        | {"level":"info","ts":1607098705.1956842,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
caddy        | run: adapting config using caddyfile: /etc/caddy/Caddyfile:6: unrecognized directive: primary

```

What's wrong?

**Comment by greenpau** [comment]
> What's wrong?

@averri , you are using `jwt` in the global context. It need to be used inside the route. I think the following will work:

```
:443 {
  tls /etc/caddy/fullchain.pem /etc/caddy/privkey.pem
}

auth.mydomain.com:443 {
    reverse_proxy  localhost:8080
}

secure.mydomain.com:443 {
  route {
    jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_name jwt_token
          token_secret my_secret
          token_issuer localhost
        }
      }
      auth_url /login
      allow roles anonymous guest admin
    }
    reverse_proxy  localhost:7878
  }
}
``` 

Please test and report back.

**Comment by averri** [comment]
Hi @greenpau, thank you for your reply.
I have tested the following code:

```text
:443 {
    tls /etc/caddy/fullchain.pem /etc/caddy/privkey.pem
}

auth.mydomain.com:443 {
    reverse_proxy  localhost:8080
}

media.mydomain.com:443 {
  route {
      jwt {
        primary yes
        trusted_tokens {
          static_secret {
            token_name jwt_token
            token_secret 6c39e5f8-5d9a-4ce6-b365-f93fe58b675a
            token_issuer taltous.com
          }
        }
        auth_url      https://auth.mydomain.com/login
        allow roles admin
      }
  reverse_proxy  localhost:7878
  }
}
```

The following behavior is happening:

1. Access the protected domain `https://media.mydomain.com` in the browser for the first time.
2. Caddy redirects to the login url https://auth.mydomain.com/login defined in `auth_url`. (**correct**)
3. The user enter the correct credentials, the backend system generates a JWT token called `jwt_token` with the claims `roles=["admin"]`. (**correct**)
4. Caddy redirects to `https://auth.mydomain.com` instead of `https://media.mydomain.com`. (**WRONG BEHAVIOR**)

Could you please help me to understand what's missing?

**Comment by greenpau** [comment]
> Caddy redirects to https://auth.mydomain.com instead of https://media.mydomain.com. (wrong behaviour)

@averri , it is hard to say, but my guess would be that token structure is not readable by `jwt` plugin. Please paste your decoded token from https://jwt.io/ here. 



> The user enter the correct credentials, the backend system generates a JWT token called

The tokens that work well with this plugin are generated by https://github.com/greenpau/caddy-auth-portal.

This is the structure I would have for my tokens.

![image](https://user-images.githubusercontent.com/3826416/101220571-e8273080-3653-11eb-8553-7f3d8a0c4c15.png)


In you case, I would need to see what your token looks like. In any case, I will make it work for your format, if necessary.

**Comment by averri** [comment]
Thanks @greenpau, this is the content of the token:

```json
{
  "exp": 1607205026,
  "origin": "simple",
  "roles": [
    "admin"
  ],
  "sub": "bob"
}
```

**Comment by averri** [comment]
Caddy is processing the token correctly, if I hit `https://media.mydomain.com` after authentication, it works well. 
The only issue is the redirect that is not working after successful authentication.

**Comment by greenpau** [comment]
@averri , the redirect after authentication should be handled by “thing” that does authentication. Jwt plugin is not in play here.

Are you talking about (1) the redirect following successful authentication, or (2) the redirect to auth.example.com following failed jwt token validation?

**Comment by averri** [comment]
@greenpau, you are right, the backend server should be responsible for sending a redirect to the URL pointed by `redirect_url` query parameter.

Is it possible to change this name `redirect_url` to something else?

**Comment by averri** [comment]
I'm closing because the root cause of the issue presented in the title of this ticket has been resolved.
