### ISSUE TITLE
Using Caddy-auth-jwt as a Token Validator

### ISSUE THREAD

**Issue by dkendall** [greenpau/caddy-auth-jwt#45]
**Describe the issue**

We're currently using Caddy as a reverse proxy (see Caddyfile below). We'd like to host application help pages on the same server (perhaps with a different subdomain), but have them protected. Our application could send a Bearer <token> authorization header with every request.

Here's an example of a token:

`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJYeXF3eE1ZbkRxR3pROVJmNTJsbSJ9.eyJpc3MiOiJodHRwczovL3BoYXJvc3NlY3VyaXR5LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZmUzYTljZDE1YWE0ZTAwNjlkZTBiZTgiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo5MDAwL2FwaS92MCIsImh0dHBzOi8vcGhhcm9zc2VjdXJpdHkuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYwODc1NTc2NywiZXhwIjoxNjA4NzYyOTY3LCJhenAiOiJramNzSkRrcFJkWmRtR2l1ZkJCNXl5YVJOVDNhM1lvWCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MiLCJwZXJtaXNzaW9ucyI6W119.pwdoDAZdwZTbok-wgDIuW9dHFlMRuHYx4H69-OZW2DALWDkzO8e8_OC1WxOXt4Rv6DKiI_ByJVN0_hiLrfK4igkVSUjpcno3vL5B2WxlZ7_7JcLWhdxyNLtXuwqpQuM3fCBdmmI3FQRaBEH1bBDcwiWdkuAd9lhVgX0uYRATRTuEgcuayPT5hWuFq6ipNDk216s79XIb4OjAtkWYhpNIbba_iZu_xmzxdtY_HEk3j40eo1lAiFoeJEoBC05QE5S2jEVnYJmUVK1f9wNkf4857VM66SkSxvQX7eSTUV3SkJHL0AbmvbSjlfD6eYu9WDaNrQDwq_HOKlfvAtqY_S-wCQ`

**Configuration**

Paste full `Caddyfile` below:

```
api.ourdomain.com {
  reverse_proxy 127.0.0.1:9000
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.1.1
http.authentication.hashes.scrypt v2.1.1
http.authentication.providers.http_basic v2.1.1
http.handlers.authentication v2.1.1
```

**Expected behavior**

Caddy-auth-jwt should ensure the token is present and valid.

If the token is not valid, it would be preferable that the server return an HTTP error (403).

If possible, caddy-auth-jwt should use **OIDC Discovery** to verify the token using the issuer's public key.

**Additional context**

**OpenID Connect Discovery** reads a file that contains OIDC configuration in JSON format:

${header.iss}/.well-known/openid-configuration
 
The plugin could obtain a URL from the 'jwks_uri' key in the JSON, and fetch this file:

${header.iss}/.well-known/jwks.json 

The plugin could then verify the token using the public key found at keys[0].

If this were implemented, and caddy-auth-jwt were to cache public keys, it should be noted that the server may encounter tokens from multiple tenants or issuers.

**Comment by greenpau** [comment]
@dkendall , thank you for opening the issue!

I think you need to use https://github.com/greenpau/caddy-auth-portal here. 

The `portal` plugin will authenticate you to Auth0 OAuth2.0, then it will issue its own token. That token would then work with `jwt` plugin.

Auth0 <-> `portal` <-> `jwt` <-> Your API

Please see how it is done for [Okta](https://github.com/greenpau/caddy-auth-portal#okta) and [other OAuth2.0 providers](https://github.com/greenpau/caddy-auth-portal#oauth-20-and-openid-connect-oidc-authentication-backend).

Also, your token has no roles information. Please read Okta's configuration and see how Okta adds "group" key into a token. I am sure similar thin exists with Auth0. Also, see [here](https://github.com/greenpau/caddy-auth-jwt#sources-of-role-information). The field could be "groups", "roles", etc.

![image](https://user-images.githubusercontent.com/3826416/103101780-38f0d000-45e7-11eb-91da-54ebb317e269.png)

I hope this answers your question.

**Comment by dkendall** [comment]
@greenpau Thanks for the quick reply!

 Unfortunately, at this point, it would be too much of a pivot to use https://github.com/greenpau/caddy-auth-portal. Our application is already validating tokens. We can of course write a new API to serve up help pages; I just thought it would be cleaner to have Caddy do it.

**Comment by greenpau** [comment]
> Our application is already validating tokens

@dkendall , you can do it, but you need to be able to pass PEM file to `jwt` plugin.

See here https://github.com/greenpau/caddy-auth-jwt#verification-with-rsa-public-keys

If Auth0 uses dynamic keys with refresh, then it is harder to accomplish.

**Comment by dkendall** [comment]
@greenpau We haven't enabled dynamic keys or key rotation at Auth0, but we are using multiple tenants, each with its own encryption key.

For our own application, we've implemented the OIDC Connect standard, and cache the public key for each tenant. Auth0 actually provides two keys. The first is the one in use, and the second is "next up", so if public key verification fails, we can try again with the other key, and if that's successful, update the cache.

**Comment by greenpau** [comment]
> the public key for each tenant.

@dkendall , in that case, you can have multiple keys:

```
trusted_public_key 1 tenan1.pem
trusted_public_key 2 tenan2.pem
trusted_public_key 3 tenan3.pem
```

**Comment by dkendall** [comment]
> @dkendall , in that case, you can have multiple keys:
> 
> ```
> trusted_public_key 1 tenan1.pem
> trusted_public_key 2 tenan2.pem
> trusted_public_key 3 tenan3.pem
> ```

Ah, that's interesting @greenpau. Does it try each key until it finds one that works?

**Comment by greenpau** [comment]
> Ah, that's interesting @greenpau. Does it try each key until it finds one that works?

It does not have to check each of the keys. Rather, an entity issuing tokens includes `kid` inside the token. 

The token you provided, has `kid` of `RXyqwxMYnDqGzQ9Rf52lm`:

![image](https://user-images.githubusercontent.com/3826416/103104343-950e2100-45f4-11eb-8d16-fd31883ead5e.png)

The configuration would be:

```
trusted_public_key RXyqwxMYnDqGzQ9Rf52lm tenan3.pem
```

**Comment by dkendall** [comment]
Well that would meet our current requirements. Thanks very much @greenpau. I'll give it a shot!

**Comment by dkendall** [comment]
Hello @greenpau,

I installed Caddy with the plugin, and configured it, but Caddy crashes on startup. The log doesn't have anything useful. Can you offer any suggestions?

files.domain.com {
  encode gzip
  root * /home/admin/workspace/public_html
  file_server
  route /* {
    jwt {
      primary yes
      disable auth_redirect_query
      option validate_bearer_header
      trusted_tokens {
        public_key {
          token_name access_token
          token_rsa_file RXyqwxMYnDqGzQ9Rf52lm /etc/caddy/jwt/RXyqwxMYnDqGzQ9Rf52lm.pem
          token_rsa_file cSqIw6oMH5WQG692cT61X /etc/caddy/jwt/cSqIw6oMH5WQG692cT61X.pem
        }
      }
      default allow
    }
  }
}

**Comment by greenpau** [comment]
@dkendall , try adding `file_server` inside `route`:

```
files.domain.com {
  route /* {
    jwt {
      primary yes
      disable auth_redirect_query
      option validate_bearer_header
      trusted_tokens {
        public_key {
          token_name access_token
          token_rsa_file RXyqwxMYnDqGzQ9Rf52lm /etc/caddy/jwt/RXyqwxMYnDqGzQ9Rf52lm.pem
          token_rsa_file cSqIw6oMH5WQG692cT61X /etc/caddy/jwt/cSqIw6oMH5WQG692cT61X.pem
        }
      }
      default allow
    }
    encode gzip
    root * /home/admin/workspace/public_html
    file_server
  }
}
```

**Comment by dkendall** [comment]
Thanks for the reply @greenpau. That didn't fix it, but I tried generating public keys using the openssl instructions [here](https://github.com/greenpau/caddy-auth-jwt#verification-with-rsa-public-keys) and it's no longer crashing.

The `pem` files I downloaded from Auth0 don't look like the openssl files. The Auth0 files start with `-----BEGIN CERTIFICATE-----` and the openssl files start with `-----BEGIN PUBLIC KEY-----`.

**Comment by dkendall** [comment]
This fixed it:

```
mv RXyqwxMYnDqGzQ9Rf52lm.pem RXyqwxMYnDqGzQ9Rf52lm.cer
openssl x509 -in RXyqwxMYnDqGzQ9Rf52lm.cer -pubkey -out RXyqwxMYnDqGzQ9Rf52lm.pem
```

**Comment by greenpau** [comment]
@dkendall , I think



@dkendall , are you all set?

**Comment by dkendall** [comment]
One more thing, @greenpau. If I access the site via a web browser (without sending a token), it redirects to `https://files.domain.com/auth`.

Is there any way to have it return a 403 instead?

I had the `disable auth_redirect_query` directive, but not the `auth_url`. I added it, but it redirects there.

**Comment by greenpau** [comment]
> Is there any way to have it return a 403 instead?

@dkendall , please read [here](https://github.com/greenpau/caddy-auth-jwt#forbidden-access). It looks like this is what you are looking for.

```
jwt {
  disable auth_redirect_query
  forbidden /custom_403.html
}```

**Comment by dkendall** [comment]
@greenpau That sounds like it _would_ work, but I don't seem to be able to get it to work. I wasn't sure if `forbidden` wants a file path or is relative to `root`, so I tried both. It still redirects to /auth.

I suppose I could set `auth_url` to `custom_403.html`, but browser redirects are a problem because I'm using this to serve files to an application, and not a browser. The application adds the authorization header, and gets files from the server. Redirects break CORS.

Speaking of the authorization header, I'm sending something like this, and it's not working:

```
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJYeXF3eE1ZbkRxR3pROVJmNTJsbSJ9.eyJpc3MiOiJodHRwczovL3BoYXJvc3NlY3VyaXR5LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZmUzYTljZDE1YWE0ZTAwNjlkZTBiZTgiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo5MDAwL2FwaS92MCIsImh0dHBzOi8vcGhhcm9zc2VjdXJpdHkuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYwODc1NTc2NywiZXhwIjoxNjA4NzYyOTY3LCJhenAiOiJramNzSkRrcFJkWmRtR2l1ZkJCNXl5YVJOVDNhM1lvWCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MiLCJwZXJtaXNzaW9ucyI6W119.pwdoDAZdwZTbok-wgDIuW9dHFlMRuHYx4H69-OZW2DALWDkzO8e8_OC1WxOXt4Rv6DKiI_ByJVN0_hiLrfK4igkVSUjpcno3vL5B2WxlZ7_7JcLWhdxyNLtXuwqpQuM3fCBdmmI3FQRaBEH1bBDcwiWdkuAd9lhVgX0uYRATRTuEgcuayPT5hWuFq6ipNDk216s79XIb4OjAtkWYhpNIbba_iZu_xmzxdtY_HEk3j40eo1lAiFoeJEoBC05QE5S2jEVnYJmUVK1f9wNkf4857VM66SkSxvQX7eSTUV3SkJHL0AbmvbSjlfD6eYu9WDaNrQDwq_HOKlfvAtqY_S-wCQ
```

How and where is the plugin expecting to find the token?

Thanks!

**Comment by greenpau** [comment]
@dkendall , there is no group/role information in your JWT token.

```json
{
  "iss": "https://pharossecurity.auth0.com/",
  "sub": "auth0|5ea91a8d6b69bc0c12e0ff7c",
  "aud": [
    "http://localhost:9000/api/v0",
    "https://pharossecurity.auth0.com/userinfo"
  ],
  "iat": 1610748123,
  "exp": 1610755323,
  "azp": "kjcsJDkpRdZdmGiufBB5yyaRNT3a3YoX",
  "scope": "openid profile email read:everythinglocal offline_access",
  "permissions": [
    "read:everythinglocal"
  ]
}
```

I suggest modifying your Auth0 config to include thing discussed [here](https://github.com/greenpau/caddy-auth-jwt#sources-of-role-information).

**Comment by greenpau** [comment]
@dkendall , see [here](https://github.com/greenpau/caddy-auth-portal#okta) how it is done for Okta.

**Comment by dkendall** [comment]
Thanks @greenpau. I'll look at adding "roles" to the token. I somehow had the idea that the plugin had default roles.

I just realized that I don't really want an invalid/missing token to result in 403 or a redirect. Our app handles a 401 by attempting to renew the access token. Is there a way to get it to return 401 instead of redirecting?

**Comment by dkendall** [comment]
@greenpau Auth0 does not have a "roles" field in its auth token, and will not allow me to add one.

Auth0 has a way to add fields, using rules, but hey require that custom fields be namespaced. So using their "rules" editor, this works:

```
function addUserRoles(user, context, callback) {
  context.accessToken['http://whatever/roles'] = ['some-role','another-role'];
  callback(null, user, context); 
}
```
... but this does not:

```
function addUserRoles(user, context, callback) {
  context.accessToken['roles'] = ['some-role','another-role'];
  callback(null, user, context); 
}
```
They also do not include `app_metadata` in the access token. It can be added using rules, but again, it has to be namespaced.

According to Auth0, roles are not part of the OAuth spec, so they won't include them without name spacing.

Auth0 supports roles, but roles are simply a collection of scopes, and the scopes are included in the authorization token.

**Comment by greenpau** [comment]
> Auth0 has a way to add fields to tokens, using rules, but hey require that custom fields be namespaced. So using their "rules" editor, I can add 'http://whatever/roles' but not 'roles'.

@dkendall , that's what you need. It could be `groups` or `roles`.  Use https://jwt.io/ to decode your tokens to see what is inside. 

> In my case, I don't care about roles or scopes. Everyone can access the files if they're authenticated. Could the plugin ignore the absence of "roles" in the token?

I don't think so.

**Comment by dkendall** [comment]
> > Auth0 has a way to add fields to tokens, using rules, but they require that custom fields be namespaced. So using their "rules" editor, I can add 'http://whatever/roles' but not 'roles'.
> 
> @dkendall , that's what you need. It could be `groups` or `roles`. Use https://jwt.io/ to decode your tokens to see what is inside.

I added roles, but the plugin still redirects to '/auth'. I assume it's because, as I mentioned, Auth0 requires that any custom fields have to be namespaced.

```
{
  "https://pharossecurity.com/roles": [
    "guest"
  ],
  "iss": "https://pharossecurity.auth0.com/",
  "sub": "auth0|5ea91a8d6b69bc0c12e0ff7c",
  "aud": [
    "http://localhost:9000/api/v0",
    "https://pharossecurity.auth0.com/userinfo"
  ],
  "iat": 1610802573,
  "exp": 1610809773,
  "azp": "kjcsJDkpRdZdmGiufBB5yyaRNT3a3YoX",
  "scope": "openid profile email read:everythinglocal offline_access",
  "permissions": [
    "read:everythinglocal"
  ]
}
```

The plugin documentation [here](https://github.com/greenpau/caddy-auth-jwt#anonymous-role) indicates that the plugin defaults to `anonymous` and `guest` if no `roles` information is found in the token.

A nice solution would  be the `claim` directive described [here](https://github.com/greenpau/caddy-auth-jwt#granting-access-with-access-lists). Either `"claim": "http://*/roles"` or `"claim": "scope"` would work.

Other than that, I guess I'll write an API to deconstruct the Auth0 token, add `roles`, and sign with a key that's shared with the plugin.

**Comment by dkendall** [comment]
@greenpau The plugin documentation [here](https://github.com/greenpau/caddy-auth-jwt#anonymous-role) indicates that the plugin defaults to `anonymous` and `guest` if no `roles` information is found in the token, and that seems to be the case at [line 360 of pkg/claims/user.go](https://github.com/greenpau/caddy-auth-jwt/blob/70e5767345bdfef377846fb8b010f412d578bf17/pkg/claims/user.go#L360).

**Comment by greenpau** [comment]
@dkendall , do you have a statement allowing anonymous?

**Comment by dkendall** [comment]
> @dkendall , do you have a statement allowing anonymous?

@greenpau I've tried `default allow` and `allow roles anonymous`.

Is there a way to see the error that the plugin is encountering?

**Comment by greenpau** [comment]
@dkendall , please post your full config.

**Comment by dkendall** [comment]
@greenpau Here's the config:

```
lib-dev.pharossecurity.com {
  encode gzip
  root * /home/admin/workspace/public_html
  file_server
  header {
    Access-Control-Allow-Origin "*"
    Access-Control-Request-Method "GET"
    Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Content-Length, Accept, Authorization"
  }
  log {
    output file /var/log/caddy.log {
      roll_size 1gb
      roll_keep 5
      roll_keep_for 720h
    }
  }
  route /* {
    jwt {
      primary yes
      disable auth_redirect_query
      allow roles anonymous
      #forbidden /403.html
      option validate_bearer_header
      trusted_tokens {
        public_key {
          token_name jwt_access_token
          token_rsa_file RXyqwxMYnDqGzQ9Rf52lm /etc/caddy/jwt/RXyqwxMYnDqGzQ9Rf52lm.pem
          token_rsa_file cSqIw6oMH5WQG692cT61X /etc/caddy/jwt/cSqIw6oMH5WQG692cT61X.pem
        }
      }
      default allow
    }
  }
}
```

Here's a bearer token:

```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJYeXF3eE1ZbkRxR3pROVJmNTJsbSJ9.eyJodHRwczovL3BoYXJvc3NlY3VyaXR5LmNvbS9yb2xlcyI6WyJndWVzdCJdLCJodHRwOi8vZGVtb3plcm8ubmV0L3JvbGVzIjpbIlN1cGVydXNlciJdLCJpc3MiOiJodHRwczovL3BoYXJvc3NlY3VyaXR5LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZWE5MWE4ZDZiNjliYzBjMTJlMGZmN2MiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo5MDAwL2FwaS92MCIsImh0dHBzOi8vcGhhcm9zc2VjdXJpdHkuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxMDgxNTk0OSwiZXhwIjoxNjEwODIzMTQ5LCJhenAiOiJramNzSkRrcFJkWmRtR2l1ZkJCNXl5YVJOVDNhM1lvWCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgcmVhZDpldmVyeXRoaW5nbG9jYWwgb2ZmbGluZV9hY2Nlc3MiLCJwZXJtaXNzaW9ucyI6WyJyZWFkOmV2ZXJ5dGhpbmdsb2NhbCJdfQ.k-vwykiHKtt6L66bijOtSCNRraauVbP50dvoaE7PvTNPvzUu4Rsny2gAIu1FCeKAJvyVk7AiZZZNLyH6069id8L20dlOATigTqcIg5NuykRokLrQjk83k5lAGkPF9JhKdlRn_NRQNZppfo9Z_BJa3nRVZgvB__B7XAXktdCNbaGagXJACULR6F0FHZNfExYYjnpQiiAOYshCVJ5rC7pQMqUHpQAp6ZQdZrlC5m82p1m4YZLtfjlJTOePYMZzmE6XY8FiyC56UjJoUCByoGH3P4WQaOeNAmiR63Dp9WcgfIHJPHlEq-ABqqPuARzOdBuXvrdMacZ4s6EYwwkew1cv5A
```

And here's the public key for the token:

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzhzLNtXgPhKWOstjluu7
cezNDqwWpfXDugsgvy+DKR3J2hMvJmomB2vSEIo2pnQ+mS5To/AxlEQaWbDG/uin
KwZ2y+xlPtulkyg8WKhPaIzaauVHOSSwctIbzO7YMP/ZDZOABo0kL57qdf18Ev1o
1MsAF7qEiGBPTww/OKtQ/fwolZaL/nzge3Zl84qBgxsJFMZPoBk+EbNOxS7kJn4N
62q6H15ofiS4RkdKAdldc5dfxRx8tCHWRJ9i2Za5eUKhX+ZSwzaWTHzE0gZGDMrT
ZZ6Mavhj95p8U8z+0I2fkWPToHMSrpaVQHCCE30JgK7Rfn2fePR0TCH2D2kS90JN
1QIDAQAB
-----END PUBLIC KEY-----
```

**Comment by greenpau** [comment]
@dkendall , the "bearer token" could be the thing here. You config says `token_name jwt_access_token`, is the token in `jwt_access_token` cookie?

**Comment by dkendall** [comment]
@greenpau the token is in the authorization header.

```
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJYeXF3eE1ZbkRxR3pROVJmNTJsbSJ9.eyJodHRwczovL3BoYXJvc3NlY3VyaXR5LmNvbS9yb2xlcyI6WyJndWVzdCJdLCJodHRwOi8vZGVtb3plcm8ubmV0L3JvbGVzIjpbIlN1cGVydXNlciJdLCJpc3MiOiJodHRwczovL3BoYXJvc3NlY3VyaXR5LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZWE5MWE4ZDZiNjliYzBjMTJlMGZmN2MiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo5MDAwL2FwaS92MCIsImh0dHBzOi8vcGhhcm9zc2VjdXJpdHkuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxMDgxNTk0OSwiZXhwIjoxNjEwODIzMTQ5LCJhenAiOiJramNzSkRrcFJkWmRtR2l1ZkJCNXl5YVJOVDNhM1lvWCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgcmVhZDpldmVyeXRoaW5nbG9jYWwgb2ZmbGluZV9hY2Nlc3MiLCJwZXJtaXNzaW9ucyI6WyJyZWFkOmV2ZXJ5dGhpbmdsb2NhbCJdfQ.k-vwykiHKtt6L66bijOtSCNRraauVbP50dvoaE7PvTNPvzUu4Rsny2gAIu1FCeKAJvyVk7AiZZZNLyH6069id8L20dlOATigTqcIg5NuykRokLrQjk83k5lAGkPF9JhKdlRn_NRQNZppfo9Z_BJa3nRVZgvB__B7XAXktdCNbaGagXJACULR6F0FHZNfExYYjnpQiiAOYshCVJ5rC7pQMqUHpQAp6ZQdZrlC5m82p1m4YZLtfjlJTOePYMZzmE6XY8FiyC56UjJoUCByoGH3P4WQaOeNAmiR63Dp9WcgfIHJPHlEq-ABqqPuARzOdBuXvrdMacZ4s6EYwwkew1cv5A
```

**Comment by greenpau** [comment]
> @greenpau the token is in the authorization header.

@dkendall , understood. That's why you have the below in your Caddyfile:

```
    jwt {
      option validate_bearer_header
    }
```

Please try the following configuration.

```
lib-dev.pharossecurity.com {
  log {
    output file /var/log/caddy.log {
      roll_size 1gb
      roll_keep 5
      roll_keep_for 720h
    }
  }
  route {
    jwt {
      primary yes
      disable auth_redirect_query
      allow roles anonymous guest
      #forbidden /403.html
      option validate_bearer_header
      trusted_tokens {
        public_key1 {
          token_name jwt_access_token
          token_rsa_file RXyqwxMYnDqGzQ9Rf52lm /etc/caddy/jwt/RXyqwxMYnDqGzQ9Rf52lm.pem
        }
        public_key2 {
          token_name jwt_access_token
          token_rsa_file cSqIw6oMH5WQG692cT61X /etc/caddy/jwt/cSqIw6oMH5WQG692cT61X.pem
        }
      }
      default allow
    }
    encode gzip
    file_server {
      root /home/admin/workspace/public_html
    }
  }
}
```

**Comment by dkendall** [comment]
@greenpau These changes made a difference. 

The plugin no longer redirects a valid request, and if I comment out the `RXyqwxMYnDqGzQ9Rf52lm` key, it does redirect (infinitely, since `/auth` is in the route, which I fixed below).

Unfortunately, it doesn't seem to respond if the request has a valid token. The Caddy log shows the GET request with status 0, length 0, duration 0.

You had removed the headers directive, but it's needed for CORS, which sends a pre-flight OPTIONS request and then a GET request if OPTIONS says cross-site is okay.

```
lib-dev.pharossecurity.com {
  log {
    output file /var/lib/caddy/access.log {
      roll_size 1gb
      roll_keep 5
      roll_keep_for 720h
    }
  }
  header {
    Access-Control-Allow-Origin "*"
    Access-Control-Request-Method "GET,OPTIONS"
    Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Content-Length, Accept, Authorization"
  }
  route {
    @options_method method OPTIONS
    respond @options_method "OK" 204
    jwt {
      primary yes
      disable auth_redirect_query
      allow roles anonymous guest
      #forbidden /403.html
      option validate_bearer_header
      trusted_tokens {
        public_key1 {
          token_name jwt_access_token
          token_rsa_file RXyqwxMYnDqGzQ9Rf52lm /etc/caddy/jwt/RXyqwxMYnDqGzQ9Rf52lm.pem
        }
        public_key2 {
          token_name jwt_access_token
          token_rsa_file cSqIw6oMH5WQG692cT61X /etc/caddy/jwt/cSqIw6oMH5WQG692cT61X.pem
        }
      }
      default allow
    }
    encode gzip
    file_server {
      root /home/admin/workspace/public_html
    }
  }
}
```

**Comment by dkendall** [comment]
@greenpau I tried sending the token in a cookie header, but the plugin didn't seem to see it (it redirected).

`Cookie: access_token={access_token}`

It seems it can also be sent as a query parameter. I tried adding `?access_token={access_token}` to the request, but again, it redirected.

**Comment by greenpau** [comment]
@dkendall , based on the snippet from [here](https://github.com/greenpau/caddy-auth-jwt/issues/45#issuecomment-761685623), I think you need help with some `caddy` basics.

```
  route /help/* {
    @options_method method OPTIONS
    header @options_method {
      Access-Control-Allow-Origin "*"
      Access-Control-Request-Method "GET, OPTIONS"
      Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Content-Length, Accept, Authorization"
    }
    respond @options_method "OK" 204
    jwt {
      primary yes
```

The `header`, `respond` and `jwt` are plugins associated with `/help/*`.

Two important things:

1. The plugin are being applied sequentially to a request.
2. The `respond` plugin is what is called "terminal" client. It means that the plugins next in line to execute will not be executed, because it terminates the chain of plugin.

Knowing the above ... where do you think `jwt` plugin should be in the chain of plugins associated with `/help/*`?

**Comment by dkendall** [comment]
@greenpau I moved the plugin to the `/help/*` route so that the redirect to `/auth` won't call the plugin (which was causing a redirect loop). The files I want to protect are in the /help/ folder.

Because our web app is on a different server than the back end, CORS comes into play. 

The browser sends an OPTIONS request before sending the GET. The OPTIONS request is used to get communication options for the pending GET, and those are provided by `header @options_method {...}`.

The `respond @options_method "OK" 204` has the effect of terminating the chain prior to the plugin getting called (for the OPTIONS request only), because OPTIONS does not include headers, which was making the plugin redirect.

This part is working correctly. OPTIONS returns 204, and GET reaches the plugin (without adding headers, thanks to the @options_method named matcher). 

If the access token is invalid or missing, the plugin replies with a 302 and a `location: /auth` header, so I'm confident that the plugin is being reached.

If the access token is present (either in the authorization header, or in a query parameter; I didn't figure out how to send it as a cookie) and the token is valid, the GET request returns nothing.

**Comment by greenpau** [comment]
> The respond @options_method "OK" 204 has the effect of terminating the chain prior to the plugin getting called (for the OPTIONS request only), because OPTIONS does not include headers, which was making the plugin redirect.

@dkendall , thank you for the explanation! I guess I need some schooling. Pretty neat 👍 thank you!

**Comment by dkendall** [comment]
> > @dkendall Pretty neat 👍 thank you!

@greenpau No problem! I've cloned the Caddy-auth-jwt repo and installed Go. I'll let you know if I can figure out what's going on.

**Comment by greenpau** [comment]
@dkendall , look at the Makefile. It will guide you.

regardless, I will write a developer guide on how to test and experiment with the plugins.

**Comment by dkendall** [comment]
Hey @greenpau. I found the issue, fixed it, and opened a Pull request.

The Auth0 token has an array for the "aud" claim, but the plugin was expecting a string.
