### ISSUE TITLE
Allow/deny audience and scope

### ISSUE THREAD

**Issue by dkendall** [greenpau/caddy-auth-jwt#48]
@greenpau I have implemented support for the Caddy options shown below.

**Configuration**

Paste full `Caddyfile` below:

```
localhost:2019 {
  route * {
    jwt {
      primary yes
      default deny
      allow audience http://localhost:9000/api/v0
      allow scopes read:everything offline_access
      allow roles anonymous guest
      validate allow_all
    }
    encode gzip
    file_server {
      root /Users/me/Documents/help-server/public_html
    }
  }
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.2.0
http.authentication.hashes.scrypt v2.2.0
http.authentication.providers.http_basic v2.2.0
http.authentication.providers.jwt v1.2.3
http.handlers.auth_portal v0.0.0-00010101000000-000000000000
http.handlers.authentication v2.2.0
```

**Additional context**

The `allow audience(s)` option lets you specify one or more audiences that appear in the token "aud" field. This field can be an array or a space-separated list in a string.

The `allow scope(s)` options  lets you specify one or more audiences that appear in the token "scope" or "scopes" field. This field can be an array or a space-separated list in a string.

Because the plugin allows access if one `allow` option passes, I've also added `validate allow_any` (default, and current behaviour), and `validate allow_all` which would require that all `allow` directives pass.

To be clear, the following directives...

```
    allow audience http://localhost:9000/api/v0
    allow scopes read:everything offline_access
    allow roles anonymous guest
    validate allow_all
```

... translate into:

```
    (audience = 'http://localhost:9000/api/v0') AND 
    (scopes='read:everything' OR scopes='offline_access') AND
    (roles='anonymous' OR roles='guest)
```

With `validate allow_any`, or default (omitted), the ANDs would be ORs.

Please let me know if you're interested in accepting this work, and I'll add unit tests and update the readme file.

**Comment by dkendall** [comment]
Implemented by https://github.com/greenpau/caddy-auth-jwt/pull/46

**Comment by greenpau** [comment]
@dkendall , please ping me on LinkedIn. Let's keep in touch!
