### ISSUE TITLE
Google oauth2 picture url

### ISSUE THREAD

**Issue by adlibdalom** [greenpau/caddy-auth-jwt#49]
**Describe the issue**
I was previously using the jwt and auth plugins for Caddy v1 and they eventually worked really well, when I got the configuration right in the end. One of the things I got through the authorization framework in v1 was an URL to the user's profile picture as part of the jwt. Now when using this and auth portal, I'm not getting that information. Is there a configuration part somewhere I've missed to get this information through?

**Configuration**
```
{
  debug
  order jwt first
}

(encoding) {
  encode gzip zstd
}

(dns) {
  tls {
    dns cloudflare xxx
  }
}

(primary-auth) {
  jwt {
    primary yes
    auth_url https://auth.xxx.xxx/oauth2/google
    trusted_tokens {
      static_secret {
        token_name access_token
        token_secret xxx
      }
    }
    allow roles superuser
  }
}

(auth) {
  jwt {
    auth_url https://auth.xxx.xxx/oauth2/google
    trusted_tokens {
      static_secret {
        token_name access_token
        token_secret xxx
      }
    }
    allow roles superuser
  }
}

auth.xxx.xxx {
  import dns
  import encoding
  route {
    auth_portal {
      path /
      cookie_domain xxx.xxx
      backends {
        google_oauth2_backend {
          method oauth2
          realm google
          provider google
          client_id xxx
          client_secret xxx
          scopes email openid
          user "@xxx.xxx$" regex add role superuser
        }
      }
      jwt {
        token_name access_token
        token_secret xxx
      }
      ui {
        links {
          "Plex" https://plex.xxx.xxx
        }
      }
    }
  }

  route /version* {
    respond * "1.0.0" 200
  }

  route {
    redir https://{hostport} 302
  }
}

plex.xxx.xxx {
  import auth
  import dns
  import encoding
  reverse_proxy http://plex.xxx:32400
}

proxy.xxx.xxx {
  import primary-auth
  import dns
  import encoding
  file_server
  root * <path>
}
```

**Version Information**
```
admin.api.load v2.3.0
admin.api.metrics v2.3.0
caddy.adapters.caddyfile v2.3.0
caddy.listeners.tls v2.3.0
caddy.logging.encoders.console v2.3.0
caddy.logging.encoders.filter v2.3.0
caddy.logging.encoders.filter.delete v2.3.0
caddy.logging.encoders.filter.ip_mask v2.3.0
caddy.logging.encoders.json v2.3.0
caddy.logging.encoders.logfmt v2.3.0
caddy.logging.encoders.single_field v2.3.0
caddy.logging.writers.discard v2.3.0
caddy.logging.writers.file v2.3.0
caddy.logging.writers.net v2.3.0
caddy.logging.writers.stderr v2.3.0
caddy.logging.writers.stdout v2.3.0
caddy.storage.file_system v2.3.0
dns.providers.cloudflare v0.0.0-20210105070211-eda8e5aa2223
http v2.3.0
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.3
http.encoders.gzip v2.3.0
http.encoders.zstd v2.3.0
http.handlers.acme_server v2.3.0
http.handlers.auth_portal v1.3.10
http.handlers.authentication v2.3.0
http.handlers.encode v2.3.0
http.handlers.error v2.3.0
http.handlers.file_server v2.3.0
http.handlers.headers v2.3.0
http.handlers.map v2.3.0
http.handlers.metrics v2.3.0
http.handlers.push v2.3.0
http.handlers.request_body v2.3.0
http.handlers.reverse_proxy v2.3.0
http.handlers.rewrite v2.3.0
http.handlers.static_response v2.3.0
http.handlers.subroute v2.3.0
http.handlers.templates v2.3.0
http.handlers.vars v2.3.0
http.matchers.expression v2.3.0
http.matchers.file v2.3.0
http.matchers.header v2.3.0
http.matchers.header_regexp v2.3.0
http.matchers.host v2.3.0
http.matchers.method v2.3.0
http.matchers.not v2.3.0
http.matchers.path v2.3.0
http.matchers.path_regexp v2.3.0
http.matchers.protocol v2.3.0
http.matchers.query v2.3.0
http.matchers.remote_ip v2.3.0
http.matchers.vars v2.3.0
http.matchers.vars_regexp v2.3.0
http.reverse_proxy.selection_policies.cookie v2.3.0
http.reverse_proxy.selection_policies.first v2.3.0
http.reverse_proxy.selection_policies.header v2.3.0
http.reverse_proxy.selection_policies.ip_hash v2.3.0
http.reverse_proxy.selection_policies.least_conn v2.3.0
http.reverse_proxy.selection_policies.random v2.3.0
http.reverse_proxy.selection_policies.random_choose v2.3.0
http.reverse_proxy.selection_policies.round_robin v2.3.0
http.reverse_proxy.selection_policies.uri_hash v2.3.0
http.reverse_proxy.transport.fastcgi v2.3.0
http.reverse_proxy.transport.http v2.3.0
pki v2.3.0
tls v2.3.0
tls.certificates.automate v2.3.0
tls.certificates.load_files v2.3.0
tls.certificates.load_folders v2.3.0
tls.certificates.load_pem v2.3.0
tls.handshake_match.sni v2.3.0
tls.issuance.acme v2.3.0
tls.issuance.internal v2.3.0
tls.issuance.zerossl v2.3.0
tls.stek.distributed v2.3.0
tls.stek.standard v2.3.0
```
**Expected behavior**
I want the jwt to contain the _picture_ url again.

**Comment by greenpau** [comment]
> One of the things I got through the authorization framework in v1 was an URL to the user's profile picture as part of the jwt. Now when using this and auth portal, I'm not getting that information. Is there a configuration part somewhere I've missed to get this information through?

@adlibdalom , thank you for opening the issue. This feature is not a part of authorization plugin.

> I want the jwt to contain the picture url again.

Are you asking for the picture URL to be a claim within JWT token issued by the `portal` plugin?

**Comment by adlibdalom** [comment]
> Are you asking for the picture URL to be a claim within JWT token issued by the `portal` plugin?

Ah, yes, I’m so new to all this, so you’re most likely right. Sorry for the confusion.
I remember parsing the cookie in JavaScript to extract the profile picture url to display the logged on user’s picture to them, which looked kind of neat.

**Comment by greenpau** [comment]
@adlibdalom , what you can do is go to “/whoami” endpoint in the “portal” plugin. You can request JSON output and it will return the information necessary to create a user card.

**Comment by greenpau** [comment]
It does not support avatar yet, but your javascript could pull the image from Gravatar.

**Comment by adlibdalom** [comment]
Yeah, I get that, but the jwt from the v1 version got a ‘picture’ claim with an URL, and with the new one it seems to be missing, so I think there’s something different with the claims.
https://github.com/tarent/loginsrv/blob/7a8566d795ccd0337dbd35078817f06ae5edccb1/model/user_info.go#L10 indicates this somewhat with the UserInfo object.
Are you saying all this info is available somewhere already? Because when I’m looking at /whoami I don’t see this info.
Sorry if I’m not explaining in a way that’s comprehensible. 😕

**Comment by adlibdalom** [comment]
Hello again.
https://developers.google.com/identity/protocols/oauth2/openid-connect#discovery points to `picture` within the `claims_supported` section in the code, so what I can't seem to figure out is how to have that claim be ”included” in the resulting jwt cookie, as it previously was with the loginsrv/caddy1 solution I employed.

**Comment by adlibdalom** [comment]
And hello again … 😛 
My very basic knowledge of programming in general, and Go in particular, would imagine that [this](https://github.com/greenpau/caddy-auth-jwt/blob/main/pkg/claims/user.go) section with the claims part could be changed to include a picture claim on a google backend, but I might be way off.

**Comment by greenpau** [comment]
>  My very basic knowledge of programming in general, and Go in particular, would imagine that this section with the claims part could be changed to include a picture claim on a google backend, but I might be way off.

@adlibdalom , I understand the ask and still thinking how I can get it to you. The difficulty is to fit this particular ask into a "big picture" of all other providers and plugins.

> would imagine that this section with the claims part could be changed

Yes, `picture` is part of the standard claims: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

**Comment by greenpau** [comment]
@adlibdalom , another question. What is the issuer of your JWT tokens? Do you use `caddy-auth-portal`?

**Comment by greenpau** [comment]
@adlibdalom , also, what application component reads the avatar URL? javascript, middleware, etc. Any screenshots?

**Comment by adlibdalom** [comment]
> @adlibdalom , another question. What is the issuer of your JWT tokens? Do you use `caddy-auth-portal`?

Yeah, I'm using `caddy-auth-portal`.

> @adlibdalom , also, what application component reads the avatar URL? javascript, middleware, etc. Any screenshots?

I'm using the caddy directive `templates` and some `javascript` code to set a variable with the jwt-info which I then parse and ”apply”.
```
<script>
    var access_token = "{{.Cookie "access_token"}}";
</script>
```

```
$(document).ready(function(){
    var userinfo = JSON.parse(atob(access_token.split('.')[1]));
    document.querySelectorAll('.name').forEach(
        el => { el.innerHTML = userinfo.name});
    document.querySelectorAll('.email').forEach(
        el => { el.innerHTML = userinfo.email});
    document.getElementById('picture').src = userinfo.picture;
...
```

**Comment by greenpau** [comment]
@adlibdalom , I am adding the parsing of `picture` in this plugin. and will make it available in `portal` plugin too.

**Comment by greenpau** [comment]
@adlibdalom , I am implementing the change for the picture. You would need to set scope as `scopes openid email profile` (the way you had it would not work). Will update the issue shortly.

**Comment by greenpau** [comment]
Will update the issue with the new `portal` version today.

**Comment by greenpau** [comment]
@adlibdalom , the `picture` is available in https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.4.4

**Comment by adlibdalom** [comment]
Nice, I just tried it and it worked straight out of the box after rebuilding with the new version, marvellous!
Thanks a bunch!
