### ISSUE TITLE
docs: document access list entry logic

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-auth-jwt#5]

**Comment by cameronelliott** [comment]
@greenpau if you have a moment sometime, I'd be curious if/how I can allow a user through with a valid token, but not necessarily any roles.

**Comment by cameronelliott** [comment]
okay, I popped it open [link](https://github.com/greenpau/caddy-auth-jwt/blob/0f63f3cd1a4134ef9d67e02716f1d518f9cb70f9/access_list.go#L65)

It looks like the only claim allowed currently is "roles".

**Comment by greenpau** [comment]
> I'd be curious if/how I can allow a user through with a valid token, but not necessarily any roles.

@cameronelliott , that would be a feature request. I was thinking about:

```
allow_anonymous: true
```

In `caddy-auth-portal`, I always grant "anonynous" role to any user.

What you are asking is bypassing role verification alltogether.

**Comment by cameronelliott** [comment]
@greenpau Yes, I think that is kind of what I am looking for. 

But, I am not using `caddy-auth-portal`.
And the system I am using does not create an "anonynous" role for every user. :disappointed: 

I am actually using Netlify widget and Gotrue as my UI and my database. Between the two,
they will create a JWT token that gets saved as a cookie.
[Gotrue](https://github.com/netlify/gotrue)
[netlify-identity-widget](https://github.com/netlify/netlify-identity-widget)

I have been trying to figure out how to get the two to create any kind of roles in the payload,
but it seems that the `gotrue` approach is to put the roles under a `app_metadata` json field.
```
{
  "app_metadata": {
    "authorization": {
      "roles": ["admin", "editor"]
    }
  }
}
```
[netlify example with app_metadata](https://docs.netlify.com/visitor-access/role-based-access-control/#external-providers)

I believe you are looking for the roles in the top level of the payload, not under a 'app_metadata' object.
Do I understand this correct?

To make a long story short, I am have a hard time making gotrue/netlify-identity-widget put roles in either the right place or wrong place in the token, so I am trying to explore methods with no roles at all, just a valid signed token with the correct shared-secret.

Any ideas?

Thanks
Cameron

**Comment by greenpau** [comment]
> I am actually using Netlify widget and Gotrue as my UI and my database. Between the two,
they will create a JWT token that gets saved as a cookie.

@cameronelliott , this is so cool! I did not know about these project! Thank you for letting me know!!! 😄 Pretty cool!

>  but it seems that the gotrue approach is to put the roles under a app_metadata json field.

I think in the process of unpacking the token, the plugin can unpack  `app_metadata => authorization => roles`.

https://github.com/greenpau/caddy-auth-jwt/blob/0f63f3cd1a4134ef9d67e02716f1d518f9cb70f9/user.go#L175-L195

I think this one is a low hanging fruit.

**Comment by greenpau** [comment]
@cameronelliott , adding support for app_metadata 😄 https://github.com/greenpau/caddy-auth-jwt/blob/7a4c7349370867e898d9f30684817a8decc97902/README.md#role-based-access-control

**Comment by greenpau** [comment]
@cameronelliott, please review https://github.com/greenpau/caddy-auth-jwt/pull/17/files. Is this what you need?

**Comment by greenpau** [comment]
> To make a long story short, I am have a hard time making gotrue/netlify-identity-widget put roles in either the right place or wrong place in the token, so I am trying to explore methods with no roles at all, just a valid signed token with the correct shared-secret.

@cameronelliott , I am working to allow exactly that!

**Comment by greenpau** [comment]
@cameronelliott , will be ready by EOD.

**Comment by cameronelliott** [comment]
You are amaing. 💯

**Comment by greenpau** [comment]
@cameronelliott , all done. Please use v1.0.5

**Comment by cameronelliott** [comment]
@greenpau Thanks for doing this, I have been pulled into another project, so I might not be able to test this for a while.
But, I think the utility to people using gotrue and the netlify-identity-widget is huge!
Thanks, Cameron

**Comment by greenpau** [comment]
> Thanks for doing this, I have been pulled into another project, so I might not be able to test this for a while.

@cameronelliott , it is all good! 😄 When you get back to it, please report your findings and file bugs! 😆 

>  But, I think the utility to people using gotrue and the netlify-identity-widget is huge!

@cameronelliott , yes ... I actually never heard about app_metadata concept before! So it was fun reading about. Once again, thank you for bringing this up.
