### ISSUE TITLE
One auth for several hosts in a domain?

### ISSUE THREAD

**Issue by sixtus** [greenpau/caddy-auth-jwt#51]
I am trying to run a single auth points for multiple hostnames in a domain.

```
auth.my.domain {
  route /auth* {
      auth_portal {
        cookie_domain my.domain
     }
  }
}
```

seems to do the trick.

However I am running into problems with the `primary` attribute. So far no combination seems to work. Do you have a working example?

I want to secure `a.my.domain` and `b.my.domain`, for login it should redirect to `auth.my.domain/auth` - all servers are configured in the same Caddyfile.

Thanks!
Hagen

**Comment by greenpau** [comment]
@sixtus , please re-open the issue in [here](https://github.com/greenpau/caddy-auth-portal/issues/new/choose). Will help you there.
