### ISSUE TITLE
Question: Does this work only with caddy-auth-portal or any OAuth 2.0 provider?

### ISSUE THREAD

**Issue by akvadrako** [greenpau/caddy-auth-jwt#52]
This looks pretty nice but one thing that's unclear to me from the README is if this only works with `caddy-auth-portal`.

I would like to use it with an OpenID Connect provider directly to avoid the 4 redirects required when using the portal in between.

Thanks for any clarification.

**Comment by greenpau** [comment]
> This looks pretty nice but one thing that's unclear to me from the README is if this only works with caddy-auth-portal.

@akvadrako ,  it can validate JWT tokens issued by other providers.

> I would like to use it with an OpenID Connect provider directly to avoid the 4 redirects required when using the portal in between.

Yes. Try getting familiar with this [doc](https://github.com/greenpau/caddy-auth-jwt#verification-with-rsa-public-keys) and [issue](https://github.com/greenpau/caddy-auth-jwt/issues/45)

**Comment by greenpau** [comment]
@akvadrako , also, you could have seamless proxying between `portal`'s OAuth backends and `jwt` module, i.e. the users will not see `portal` at all.

**Comment by akvadrako** [comment]
Thanks, I am new to OAuth 2.0 so I didn't realize the signing key is the key to make this work. I'll try that way first since it seems similar.

**Comment by greenpau** [comment]
> Thanks, I am new to OAuth 2.0 so I didn't realize the signing key is the key to make this work. I'll try that way first since it seems similar.

@akvadrako , fyi, some providers rotate keys (e.g. Google OAuth). In that case `portal` is your best bet.
Good luck exploring! Please don't hesitate asking questions.

**Comment by akvadrako** [comment]
@greenpau So just to report back, I was not able to get `caddy-auth-jwt` to work with an OIDC provider directly. I was trying to use [glewlwyd](https://github.com/babelouest/glewlwyd) because it seemed the like easiest to install. There were a few issues:

1. The auth endpoint can return a `code` which can be used to fetch the token, but `auth-jwt` doesn't seem to understand codes. 
2. The auth endpoint can return a `token` but only as a hash parameter in the URL, which `auth-jwt` cannot access.
3. It only supports the `redirect_uri` parameter, not a `redirect_url`. I could workaround this by hard-coding it.

**Comment by greenpau** [comment]
>  to work with an OIDC provider directly

@akvadrako, yes, OIDC provider will not work directly. That's why `portal` exists. You could make it completely seamless with `redirect_url` and point it to `auth/oauth/provider_name`. A user would not even notice the `portal`.

**Comment by akvadrako** [comment]
I disagree they won't notice; it requires four redirects which normally will take some time.
