### ISSUE TITLE
Use env placeholders for OIDC Client ID/Secret

### ISSUE THREAD

**Issue by optiz0r** [greenpau/caddy-auth-jwt#54]
Hi,

Not sure if this is plugin-specific behaviour or a Caddy limitation.

I would like to be able to template in the OIDC client ID and secret using `{env.*}` placeholders. This would prevent the secrets needing to be persisted to disk. Currently I have env vars set at runtime, but if I try to use an env placeholder, then the literal strings `{env.OIDC_CLIENT_ID}` is being used in the authorisation request to the OIDC provider, which rejects it for not being a known client id.

**Configuration**

Trimmed for brevity, only relevant directives shown

```
https://auth.example.com {
  route /auth* {
    auth_portal {
      backends {
        generic_oauth2_backend {
          method oauth2
          # These placeholders do not interpolate
          client_id {env.OIDC_CLIENT_ID}
          client_secret {env.OIDC_CLIENT_SECRET
        }
      }
      jwt {
        token_name access_token
        # This placeholder interpolates OK
        token_secret {env.OIDC_RESIGNING_SECRET}
      }
    }
  }
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.6
http.handlers.auth_portal v1.4.3
http.handlers.authentication v2.3.0
```

**Expected behavior**

Client ID/Secret should accept placeholders

**Comment by greenpau** [comment]
@optiz0r , I will be working on it sometime next week.

**Comment by greenpau** [comment]
Note: per conversation with @francislavoie, he recommends. Leaving it here for the reference.

```
I recommend checking out the caddy codebase and poking around, looking at how existing modules do it is the best way to go. Basically you're looking for places where ReplacerCtxKey is used. Basically the replacer is put in Context at the start of each request, and it can used to grab the replacer instance. Looks like this: repl := r.Context().Value(caddy.ReplacerCtxKey).(*caddy.Replacer)

{$ENV} only works for the Caddyfile, but {env.*} works for all config adapters
```

**Comment by greenpau** [comment]
@optiz0r , have you tried using `{$ENV}`?

**Comment by francislavoie** [comment]
To be clear, what I was saying is that `{$ENV}` will work regardless of any changes to the codebase, because it's a feature implemented in the Caddyfile adapter: https://caddyserver.com/docs/caddyfile/concepts#environment-variables

The difference is that `{$ENV}` is replaced at Caddyfile adapt time, whereas `{env.*}` is replaced at runtime, but only if the module passes configuration values through the Replacer, i.e. the mechanism used to transform config placeholders into context-specific values. If this module doesn't use the replacer, then `{env.*}` will not work -- so replacer support needs to be implemented in this module for that to work.

**Comment by optiz0r** [comment]
> @optiz0r , have you tried using {$ENV}?

I had not tried this, but just have and indeed it does work, thanks!

> The difference is that {$ENV} is replaced at Caddyfile adapt time

In this case, this should be fine, as the values don't change once the process starts up (and if they ever do change, the container scheduler will trigger an explicit reload anyway).

**Comment by greenpau** [comment]
@optiz0r , with the recent changes to configuration syntax, you would need to change.

```
https://auth.example.com {
  route /auth* {
    authp {
      backends {
        generic_oauth2_backend {
          method oauth2
          # These placeholders do not interpolate
          client_id {env.OIDC_CLIENT_ID}
          client_secret {env.OIDC_CLIENT_SECRET}
        }
      }
      crypto key sign-verify {env.OIDC_RESIGNING_SECRET}
    }
  }
```

FYI, @francislavoie gave me a few pointers on how to implement placeholders.

We will see how I can get them integrated.

```
client_id {env.OIDC_CLIENT_ID}
client_secret {env.OIDC_CLIENT_SECRET}
crypto key sign-verify {env.OIDC_RESIGNING_SECRET}
```

**Comment by greenpau** [comment]
Need to add replacers in these places:

1. https://github.com/greenpau/caddy-auth-portal/blob/c3957cd0e8fa870a86f762783ee1ec11a4c85ab9/caddyfile.go#L292-L299
2. https://github.com/greenpau/caddy-auth-portal/blob/c3957cd0e8fa870a86f762783ee1ec11a4c85ab9/caddyfile.go#L239-L243
3. https://github.com/greenpau/caddy-auth-portal/blob/c3957cd0e8fa870a86f762783ee1ec11a4c85ab9/caddyfile.go#L173-L184

**Comment by greenpau** [comment]
Additionally, need to add it here:

https://github.com/greenpau/caddy-auth-jwt/blob/9676ded0e0ca1b71c6b9470da146aeac50954227/caddyfile.go#L118-L129

**Comment by greenpau** [comment]
This now resolved in https://github.com/greenpau/caddy-auth-portal/commit/f7970b46232ec7846b89dc6e50a8b697f16b1bcf
