### ISSUE TITLE
Error during parsing: auth backend public_key subdirective has no value

### ISSUE THREAD

**Issue by sernik** [greenpau/caddy-auth-jwt#59]
Caddy does not start `run: adapting config using caddyfile: parsing caddyfile tokens for 'jwt': /etc/caddy/Caddyfile:20 - Error during parsing: auth backend public_key subdirective /etc/caddy/01-es256-public.pem has no value`.

**Configuration**

```
{
	debug
	auto_https off
	order jwt first
}

:80 {

	jwt {
		disable auth_redirect
		option validate_bearer_header
		primary yes
		trusted_tokens {
			static_secret {
				token_name access_token
				token_secret UFemXdzF6tqxFw5o9GfMQR5m2u5N9WK6
			}
			public_key {
				token_name access_token
				token_es256_file keyid01 /etc/caddy/01-es256-public.pem
			}
		}
    }

	log

	reverse_proxy http://127.0.0.1:3000

}
```

**Version Information**
```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
http.handlers.authentication v2.3.0
```

**Expected behavior**

Caddy starts fine with this configuration, without `public_key {…}` block.

**Additional context**

What is the use of a keyid in this setup?

**Comment by greenpau** [comment]
@sernik , I am in the process of refactoring the plugin. The ES are not supported. Once I complete the refactoring in the next couple weeks, I will let you know and you will retry.

As to the key ID, when tokens arrive with “kid” field, the value is matched to the value of the key specified in the config. If there is no kid, kid of 0 could be assumed.

**Comment by sernik** [comment]
Thank you, waiting then.

**Comment by greenpau** [comment]
@sernik , the ECDSA key pair are now supported. See https://github.com/greenpau/caddy-auth-jwt#verification-with-rsa-and-ecdsa-keys
