### ISSUE TITLE
Unauthenticated POST request will be redirected with a GET (status 302)

### ISSUE THREAD

**Issue by AtomBaf** [greenpau/caddy-auth-jwt#60]
**Describe the issue**

When a POST request is sent, without credentials, the plugin will redirect to the auth endpoint. 
The status code is 302, so the client will perform a GET request to the auth location.

**Configuration**

Any caddyfile like this one : https://github.com/greenpau/caddy-auth-jwt#caddyfile

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.3
http.handlers.authentication v2.3.0
```

**Expected behavior**

I expect that, in case of a POST (or PUT, DELETE,...) the redirect status code to be 307.
see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307 for reference

**Additional context**

I suspect this could be a small change here: https://github.com/greenpau/caddy-auth-jwt/blob/main/pkg/handlers/redirect.go#L40

Thank you!

**Comment by greenpau** [comment]
> I suspect this could be a small change here: https://github.com/greenpau/caddy-auth-jwt/blob/main/pkg/handlers/redirect.go#L40

@AtomBaf, thank you for opening the issue. The 307 change would have to wait for my completion of the plugin rewrite (probably one-two weeks). I will post back here when I am done.

Additionally, the change will also need to add Caddy directive, e.g. `redirect <HTTP_STATUS_CODE>`.

**Comment by AtomBaf** [comment]
Thx for your quick answer @greenpau 
About your last sentence, do you mean that I will have to write a dedicated ```redirect``` directive for each http method? Isn't in the ```redirect.go``` that the request method could be checked and depending on it, return a 302 or 307 status ?

**Comment by greenpau** [comment]
> do you mean that I will have to write a dedicated redirect directive for each http method?

No.  By default, it would do the `302` redirect. However, that would be possible to change to any other status code a user desires, e.g. `307`, like you want.

> Isn't in the redirect.go that the request method could be checked and depending on it, return a 302 or 307 status ?

The `redirect.go` could implement whatever logic one wants. However, the `caddyfile.go` determines which configuration options would be used. My reference was about the configuration.

**Comment by greenpau** [comment]
@AtomBaf , also, thinking about POST to GET transition. It is a common practice to redirect this way, because a user will not be able to resubmit on refresh.

**Comment by AtomBaf** [comment]
In my case, redirecting a POST to a GET is meaningless, the HTTP client should auto-connect and auto-login without the user noticing the redirections. Most of the calls I'm doing are made with python `requests` and since the endpoints I'm calling are `POST` handlers, on a first try, I always end with `407` Method not allowed statuses.

My current workaround for now is to systematically send a `GET` pre-flight request when the http session is starting with `POST`. This is weird.

The `307` code is exactly for this purpose. Yes, you don't want the client to re-send a `POST` request because it will/could modify server-side resources, but in our case of a missing authentication and SSO, the `POST`has to be repeated, don't you think ?

Note: I'm not sure of all the http client behavior when they receive a `307` code, but the RFC looks pretty clear on the specifications.

**Comment by greenpau** [comment]
@AtomBaf , please retry what your are doing with the latest version of the plugin.

**Comment by AtomBaf** [comment]
thx for your response @greenpau, but sorry, looking at this line https://github.com/greenpau/caddy-auth-jwt/blob/main/pkg/handlers/redirect.go#L40 I cannot see how the plugin can send anything other than a `302` status code. Is there something I'm missing?

**Comment by greenpau** [comment]
@AtomBaf , at the moment, I am still trying to understand the issue here. The first step is having up-do-date plugin and visible config. Then, I would need a diagram (https://www.diagrams.net/) of how you think it should work.

**Comment by AtomBaf** [comment]
Hi

This is what is happening today:

```
+-------------+                                                                         +-------+                                             +-------+                               +---------+
| HTTPClient  |                                                                         | Caddy |                                             | Auth  |                               | Backend |
+-------------+                                                                         +-------+                                             +-------+                               +---------+
       |                                                                                    |                                                     |                                        |
       | POST request to the backend without auth                                           |                                                     |                                        |
       |----------------------------------------------------------------------------------->|                                                     |                                        |
       |                                                                                    |                                                     |                                        |
       |     No auth present, so send redirect to auth URL (302, which is bad in that case) |                                                     |                                        |
       |<-----------------------------------------------------------------------------------|                                                     |                                        |
       |                                                                                    |                                                     |                                        |
       | GET request to the auth app (Common behaviour of lot of http clients)              |                                                     |                                        |
       |----------------------------------------------------------------------------------->|                                                     |                                        |
       |                                                                                    |                                                     |                                        |
       |                                                                                    | Request is reverse proxified to the auth app        |                                        |
       |                                                                                    |---------------------------------------------------->|                                        |
       |                                                                                    |                                                     |                                        |
       |                                                                                    |                                                     | Verify auth, create token, etc...      |
       |                                                                                    |                                                     |----------------------------------      |
       |                                                                                    |                                                     |                                 |      |
       |                                                                                    |                                                     |<---------------------------------      |
       |                                                                                    |                                                     |                                        |
       |                                                                                    |     send redirect to the original backend URL (307) |                                        |
       |                                                                                    |<----------------------------------------------------|                                        |
       |                                                                                    |                                                     |                                        |
       |                                         Redirect response proxified by caddy (307) |                                                     |                                        |
       |<-----------------------------------------------------------------------------------|                                                     |                                        |
       |                                                                                    |                                                     |                                        |
       | GET request to the backend this time with valid auth                               |                                                     |                                        |
       |----------------------------------------------------------------------------------->|                                                     |                                        |
       |                                                                                    |                                                     |                                        |
       |                                                                                    | GET request proxified by caddy                      |                                        |
       |                                                                                    |--------------------------------------------------------------------------------------------->|
       |                                                                                    |                                                     |                                        |
       |                                                                                    |                                                    405 Error response, method is not allowed |
       |                                                                                    |<---------------------------------------------------------------------------------------------|
       |                                                                                    |                                                     |                                        |
       |                                                  405 Error proxified to the client |                                                     |                                        |
       |<-----------------------------------------------------------------------------------|                                                     |                                        |
       |                                                                                    |                                                     |                                        |
```

You can see in this sequence that the original `POST` request is finally transformed into a `GET` request (Step 2 & 3).

I would like the JWT plugin to return a `307 Temporary Redirect` status code instead of the `302 Found`.

As stated [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302), when sending a `302`code, the client might change its original request method:
>Even if the specification requires the method (and the body) not to be altered when the redirection is performed, not all user-agents conform here - you can still find this type of bugged software out there. It is therefore recommended to set the 302 code only as a response for GET or HEAD methods and to use 307 Temporary Redirect instead, as the method change is explicitly prohibited in that case.

**Comment by greenpau** [comment]
> POST request to the backend without auth 

@AtomBaf , what is the type of backend, i.e. OAuth, SAML, etc.?

**Comment by AtomBaf** [comment]
Custom webserver, handling authentication with corporate SSO/kerberos.
The initial POST request is just a random request to the backend, without any credential. I would like the authentication mechanism to automatically handle all the sequence.

**Comment by greenpau** [comment]
> I would like the JWT plugin to return a 307 Temporary Redirect status code instead of the 302 Found.

@AtomBaf , I will add a configuration option for this.

need to add the option here:

https://github.com/greenpau/caddy-auth-jwt/blob/30c48c870a68107a7808cde808b3e3453be9c762/pkg/authz/authorizer.go#L157-L158

and take into account and return proper status code on redirect.

https://github.com/greenpau/caddy-auth-jwt/blob/4f3e27a82d06c36bff4559ec000005393a08795e/pkg/handlers/redirect.go#L44

Add the following configuration parameter:

```
AuthRedirectStatusCode int                     `json:"auth_redirect_status_code,omitempty" xml:"auth_redirect_status_code,omitempty" yaml:"auth_redirect_status_code,omitempty"`
```

Next, add it in here

https://github.com/greenpau/caddy-auth-jwt/blob/30c48c870a68107a7808cde808b3e3453be9c762/pkg/authz/authorizer.go#L157-L158

as:

```
			redirOpts["auth_redirect_status_code"] = m.AuthRedirectStatusCode
```

Next, add Caddyfile parser directive `set redirect status <CODE>`: 

https://github.com/greenpau/caddy-auth-jwt/blob/4f3e27a82d06c36bff4559ec000005393a08795e/caddyfile.go#L268-L284

Side note: reimplement `AuthRedirectQueryParameter`
