### ISSUE TITLE
Invalid documentation for v1.2.7

### ISSUE THREAD

**Issue by samhuss** [greenpau/caddy-auth-jwt#66]
**Describe the issue**
The documentation of jwt usage doesn't match the required directives in v1.2.7

**Configuration**
    jwt {
      primary yes
      crypto key verify 0e2fdcf8-6868-41a7-884b-7308795fc286
      crypto key e1008f2d verify testdata/rskeys/test_2_pri.pem
      set auth url /auth
      allow roles anonymous guest admin
      allow roles superadmin
      allow roles admin editor viewer
      allow roles AzureAD_Administrator AzureAD_Editor AzureAD_Viewer
      allow roles everyone Everyone
    }

**Version Information**
http.authentication.hashes.bcrypt v2.4.0
http.authentication.hashes.scrypt v2.4.0
http.authentication.providers.http_basic v2.4.0
http.handlers.authentication v2.4.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.5

```
Error during parsing: parsing caddyfile tokens for 'jwt': /home/sam/src/dev/config/odoo-local/Caddyfile:220 - Error during parsing: unsupported root directive: crypto
```

**Expected behavior**
Correct sample code for Caddy v2

Describe expected behavior.

**Additional context**
xcaddy couldn't build from master and always building from v.1.2.7. The source code for v1.2.7 contains old assets directory with correct sample config file, that's how I realized the deviation between the released version and the documented one.

**Comment by sseppola** [comment]
This left me searching for a while so for anyone else who arrives here: The master branch is ahead of the latest release, so check the instructions of the release you are using. 

https://github.com/greenpau/caddy-auth-jwt/tree/1f0825e606c2f6493f097ffacbaad60f42c8b61f#table-of-contents
