### ISSUE TITLE
Verify value of specific claim

### ISSUE THREAD

**Issue by chris-rock** [greenpau/caddy-auth-jwt#69]
**Describe the issue**

I would love to verify that a specific claim with a specific value is set, otherwise I would like to deny users. I searched through the latest documentation and I could not find a definitive answer.

**Configuration**

n/a

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.1
http.authentication.hashes.scrypt v2.4.1
http.authentication.providers.http_basic v2.4.1
http.handlers.authentication v2.4.1
http.authentication.providers.jwt v1.2.8-0.20210603001308-23eb6ccc2226
```

**Expected behavior**

I am able to do simple checks for exact match of claim values

**Additional context**

**Comment by greenpau** [comment]
@chris-rock , thank you for the issue! Please provide a few examples of what you want to accomplish. I will try answering it here.

**Comment by chris-rock** [comment]
I just wanted to check if the "iss" field has a specific value. Some token providers use the same public key (eg. firebase). Therefore the pure validity check of the token is not enough to ensure its an authenticated user.

**Comment by greenpau** [comment]
@chris-rock , the non-released HEAD contains what you need, but it is not incorporated into Caddyfile yet.

The gist would likely be:

```
acl rule {
  comment permit issuers containing foobar keyword
  partial match issuer foobar
  action allow log
}
```

See here for some samples:

https://github.com/greenpau/caddy-auth-jwt/blob/23eb6ccc2226e3159b2ef3c73ebb8415e91ed3ca/pkg/acl/acl_test.go#L81-L90

The `RuleConfiguration` holds the configuration of each individual rule in an ACL.

Additionally, here is how the config lines being parsed from a rule:

https://github.com/greenpau/caddy-auth-jwt/blob/23eb6ccc2226e3159b2ef3c73ebb8415e91ed3ca/pkg/acl/condition.go#L602-L656

The various field you can match on (e.g. `"issuer": "iss"`) are here:

https://github.com/greenpau/caddy-auth-jwt/blob/23eb6ccc2226e3159b2ef3c73ebb8415e91ed3ca/pkg/acl/condition.go#L27-L62

I will ping you back on this issue to test when Caddyfile integration is ready.

**Comment by chris-rock** [comment]
That is great. Thank you @greenpau No rush on this from my side.

**Comment by greenpau** [comment]
@chris-rock , the https://github.com/greenpau/caddy-auth-jwt/commit/20817c5c42383d90bf2cf429d88e874cde9c0903 adds Caddyfile directive for the building of complex ACLs.

Added documentation [here](https://github.com/greenpau/caddy-auth-jwt/blob/main/README.md#primer).

By and large, it is self-explanatory. However, do not hesitate to reopen this issue and ask questions.
