### ISSUE TITLE
How do I use this in Caddyfile?

### ISSUE THREAD

**Issue by vtoma** [greenpau/caddy-auth-jwt#7]
Hi, is there a directive for Caddyfile? 
Thanks!

**Comment by greenpau** [comment]
> Hi, is there a directive for Caddyfile?

@vtoma , currently, non-JSON configuration is not supported. Thank you for this issue! I am going to add Caddyfile parser shortly.

**Comment by vtoma** [comment]
Hey @greenpau , any news on directive for Caddyfile?

**Comment by greenpau** [comment]
@vtoma , did not have time to get to it yet. 😢

**Comment by vtoma** [comment]
@greenpau can some money compensation help to get things go faster? :)

**Comment by greenpau** [comment]
> can some money compensation help to get things go faster? :)

@vtoma, everything is possible :-) please reach out on LinkedIn :-)

**Comment by greenpau** [comment]
@vtoma , I asked caddy team to help with the Caddyfile conversion. I will hear more about it next week. Will keep you posted.

**Comment by vtoma** [comment]
Thanks!

**Comment by sk123** [comment]
Awesome, I came to ask this same question (in my first ever github post)! Caddyfile support would help me a ton.  Thanks for all you do.

**Comment by greenpau** [comment]
@vtoma , @sk123 , prepare to test by the EOW! 😄 See #21 
very close to making it work with some basic settings.

**Comment by greenpau** [comment]
@vtoma , @sk123 , see reference config: https://github.com/greenpau/caddy-auth-portal#secure-prometheus

**Comment by sk123** [comment]
you rock! i haven't had a chance to play with it; will try tonight, but definitely this weekend.  thank you thank you!
> @vtoma , @sk123 , see reference config: https://github.com/greenpau/caddy-auth-portal#secure-prometheus
