### ISSUE TITLE
xcaddy doesn't add the module

### ISSUE THREAD

**Issue by sixtus** [greenpau/caddy-auth-jwt#70]
**Describe the issue**

```$ xcaddy build --with github.com/greenpau/caddy-auth-jwt```

I tried this on several machines (linux/mac) and it just doesn't work...

**Configuration**

Clean installation of go (even remove ~/go)

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
$ ./caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.1
http.authentication.hashes.scrypt v2.4.1
http.authentication.providers.http_basic v2.4.1
http.handlers.authentication v2.4.1
http.authentication.providers.jwt v1.2.7
```

**Expected behavior**

expecting the caddy-auth-jwt to be in the list

**Comment by sixtus** [comment]
```
$  ./caddy list-modules -versions|grep jwt
http.authentication.providers.jwt v1.2.7
```

Could this be part of the problem?

**Comment by sixtus** [comment]
Ah, https://github.com/greenpau/caddy-auth-jwt/blob/main/plugin.go#L39 - so maybe it is added, however

```
$ ./caddy validate --config assets/conf/v2/Caddyfile
2021/06/08 14:14:51.349	INFO	using provided configuration	{"config_file": "assets/conf/v2/Caddyfile", "config_adapter": ""}
validate: adapting config using caddyfile: parsing caddyfile tokens for 'route': assets/conf/v2/Caddyfile:25 - Error during parsing: parsing caddyfile tokens for 'jwt': assets/conf/v2/Caddyfile:15 - Error during parsing: unsupported root directive: crypto
```

That was my original issue, it just looked like the module isn't added.

**Comment by sixtus** [comment]
Ah, I think that's all I need to unstuck myself:

$ xcaddy build --with github.com/greenpau/caddy-auth-jwt=.
$ ./caddy validate --config assets/conf/v2/Caddyfile
[...]
Valid configuration

Thanks, that was totally not obvious... well now it is :)

If I have time I do a PR for the readme, not promising anything.

And to answer the question: my boss hacked a sso jwt portal for his php toys and after showing him your plugin, he changed his to be compatible.

So finally, I get to try it out :)

Your work & help is much appreciated!

Cheers from Berlin!
Hagen

**Comment by greenpau** [comment]
@sixtus , I just release the latest new version. Try building without the dot.

```
xcaddy build --with github.com/greenpau/caddy-auth-jwt@latest
```
