### ISSUE TITLE
Parse caddy http placeholders

### ISSUE THREAD

**Issue by lbreitk** [greenpau/caddy-auth-jwt#71]
**Describe the issue**

The configuration file doesn't seem to parse http placeholders, as seen [here](https://caddyserver.com/docs/json/apps/http/)

**Configuration**

relevant configuration snippet (using many separate caddy files)

```
:443 {
  import tls-public
  respond /health 200 {
    body '{"status":"ok"}'
    close
  }
  route * {
    jwt {
      primary yes
      enable claim headers
      trusted_tokens {
        static_secret {
          token_name    access_token
          token_secret  [redacted]
        }
      }
      auth_url "https://example.com"
      forbidden "https://example.com/assets/403?referral={uri}"
    }
  }
}
```
**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.1
http.authentication.hashes.scrypt v2.4.1
http.authentication.providers.http_basic v2.4.1
http.handlers.authentication v2.4.1
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
```

**Expected behavior**
 
The placeholder `{uri}` (or any other http placeholder) should resolve the URI, instead of `{http.request.uri}`.

**Additional context**

I'm adding a custom 403 page, and want to pass the URL that the user is being denied access to, to the page so it can be output on the page and also added to the mailto link.

![image](https://user-images.githubusercontent.com/77999616/121271201-0296cc80-c878-11eb-80f6-588ea40cf04a.png)
![image](https://user-images.githubusercontent.com/77999616/121271238-19d5ba00-c878-11eb-89da-ef3c383bce8c.png)

**Comment by lbreitk** [comment]
@greenpau any thoughts on this? Should I post this as a request somewhere else or what?

**Comment by greenpau** [comment]
@lbreitk , the reason this is unattended - I am not well-versed with placeholders. I would love to implement it, but I need some help here. 

Linking #54, and  because it looks like it is a similar problem.

The challenge for me is that whatever placeholder code would do, it needs to be implemented here: https://github.com/greenpau/caddy-auth-jwt/blob/c1030cb4d89d435970fae848c97d8ae48ae0cc98/plugin.go#L57-L79

**Comment by lbreitk** [comment]
@greenpau understood. Thanks for the explanation! :)

**Comment by greenpau** [comment]
The reason it needs to be implemented in `plugin.go` is because all the code in `pkg` does not use caddy. It could be used with other Go frameworks, e.g. gin.

**Comment by greenpau** [comment]
@lbreitk , please test this with 05f8352.

Here is my configs.

1) The following config line results in redirect `https://localhost:8443/errors/forbidden.html?referral=https://localhost:8443/goapi-dev/` (URL)

```
set forbidden url /errors/forbidden.html?referral={url}
```

2) The following config line results in redirect `https://localhost:8443/errors/forbidden.html?referral=/goapi-dev/` (URI only)

```
set forbidden url /errors/forbidden.html?referral={uri}
```

Here is how your config might look like with the latest version:

```
:443 {
  import tls-public
  respond /health 200 {
    body '{"status":"ok"}'
    close
  }
  route * {
    jwt {
      primary yes
      inject headers with claims
      crypto key verify [redacted]
      set auth url "https://example.com"
      set forbidden url "https://example.com/assets/403?referral={url}"
    }
  }
}
```

**Comment by greenpau** [comment]
@lbreitk , please test, and if all is OK, close.

**Comment by lbreitk** [comment]
@greenpau Thanks so much for trying to fix this for me! What's the best way to test? I tried using `xcaddy` to build a version of caddy using `--with github.com/greenpau/caddy-auth-jwt@05f83528b164ef5e7a1bcacc77a5b36087906faa` but ran into some errors. Maybe I'm missing something? Is there a better way to do this?

**Comment by greenpau** [comment]
@lbreitk you could use caddy download page too. With "latest" tag. The last release has the config.

**Comment by lbreitk** [comment]
@greenpau that will be *so* much easier, thanks! I go test that as soon as I get a few minutes :)

**Comment by lbreitk** [comment]
Well, got it downloaded, but it seems like you changed the auth-portal config since the last time I used it? It's not liking my config now that was working previously

**Comment by greenpau** [comment]
@lbreitk , that’s why I provided the replacement config.

**Comment by greenpau** [comment]
See above ^

**Comment by lbreitk** [comment]
Ah, I see. I guess I should post my current auth-portal config too then. The problem is, I have my config broken out in a lot of small configs - 13 some configs in my `sites-available` directory, including my auth portal config and default config, plus a few files for my includes and default snippets and what not. Hard to post the whole thing, and it all has to be sanitized before sharing.

```
https://auth.1.example.com https://auth.2.example.com {
  import tls-public
  route /* {
    auth_portal {
      path /
      cookie_domain   1.example.com
      cookie_domain   2.example.com
      cookie_path     /
      cookie_lifetime 3600
      backends {
        keycloak_oauth {
          method              oauth2
          realm               1
          provider            generic
          metadata_url        https://sso.1.example.com/auth/realms/bar1/.well-known/openid-configuration
          base_auth_url       https://sso.1.example.com/auth/realms/bar1
          client_id           proxy-auth
          client_secret       [redacted]
          scopes              openid email profile roles
          identity_token_name access_token
        }
      }
      jwt {
        token_name        access_token
        token_secret      [redacted]
        token_lifetime    3600
      }
      ui {
        theme basic
        static_asset "assets/403" "text/html" /opt/caddy/config/403.html
        static_asset "assets/test" "text/html" /opt/caddy/config/test.html
        logo_url "[redacted]"
        logo_description "stuff"
        links {
          [links and stuff here]
        }
      }
    }
  }
}
```

**Comment by greenpau** [comment]
@lbreitk , it is quiet simple:

```
https://auth.1.example.com https://auth.2.example.com {
  import tls-public
  route {
    authp {
      crypto default token lifetime 3600
      crypto key sign-verify [redacted]
      cookie domain 1.example.com
      cookie lifetime 3600
      backends {
        keycloak_oauth {
          method              oauth2
          realm               1
          provider            generic
          metadata_url        https://sso.1.example.com/auth/realms/bar1/.well-known/openid-configuration
          base_auth_url       https://sso.1.example.com/auth/realms/bar1
          client_id           proxy-auth
          client_secret       [redacted]
          scopes              openid email profile roles
          identity_token_name access_token
        }
      }
      ui {
        theme basic
        static_asset "assets/403" "text/html" /opt/caddy/config/403.html
        static_asset "assets/test" "text/html" /opt/caddy/config/test.html
        logo url "[redacted]"
        logo description "stuff"
        links {
          [links and stuff here]
        }
      }
      enable source ip tracking
    }
  }
}
```

![image](https://user-images.githubusercontent.com/3826416/123515316-ead78a80-d664-11eb-8582-f2bc8773239c.png)

The `crypto` part mimics https://github.com/greenpau/caddy-auth-jwt#plugin-syntax.

Please let me know if you run in issues with the above

**Comment by greenpau** [comment]
@lbreitk , also, side note, I don't think the following line ever worked as intended. 

```
      cookie_domain   1.example.com
      cookie_domain   2.example.com
```

I can add support for this in a future if necessary.

**Comment by lbreitk** [comment]
I've got almost all of this working, but I'm running into more issues. It feels like your documentation isn't matching the current state of the modules, which is a bit frustrating. Now I'm getting errors that I apparently I *have* to have an "allow" rule in my default JWT config, which I don't want - I want all my sites to default to deny access and have a per-site role access. README.md says that you set `acl default allow` or whatever under `jwt{}` but caddy doesn't start and says that `acl` isn't allowed in the root directive. But without editing my other site configs, it just lets all users in now and doesn't seem to be checking their OpenID roles at all.

Example:

`default`:
```
:443 {
  import tls-public
  respond /health 200 {
    body '{"status":"ok"}'
    close
  }
  route * {
    jwt {
      primary yes
      inject headers with claims
      crypto key verify [redacted]
      set auth url "https://auth.1.example.com"
      set forbidden url "https://auth.1.example.com/assets/403?referral={url}"
      allow roles null
    }
  }
}
```

`consul`:
```
https://consul.1.example.com https://consul.2.example.com {
  import defaults
  import tls-public
  reverse_proxy http://consul.service.consul.2.example.com:8500
  route * {
    jwt {
      allow roles res-consul-access
    }
  }
}
```

What I want to happen is that a user is denied if they aren't in an ldap group (passed through the OpenID claim and then through to the auth-portal/jwt). This was working in previous versions. Now it seems that it's not. I've tried following the readme on the github page it seems to not be consistent. I.E. I tried adding `acl default deny` to either the default or to a specific site, which is what the documentation says to do for using ACLs, but caddy says `Error during parsing: unsupported root directive: acl`

**Comment by greenpau** [comment]
@lbreitk , have you tried this?

```
https://consul.1.example.com https://consul.2.example.com {
  import defaults
  import tls-public
  route {
    jwt {
      primary yes
      crypto key ...
      allow roles res-consul-access
    }
    reverse_proxy http://consul.service.consul.2.example.com:8500
  }
}
```

**Comment by lbreitk** [comment]
greenpau, I appreciate your help, as always, but I'm confused how that helps? I have a ton of sites, that's why I made a dedicated default configuration rather than making any one of the sites the "primary".

I'm using the config you posted here: https://github.com/greenpau/caddy-auth-jwt/issues/71#issuecomment-868057155 for the "default" site config, it defines the primary jwt

**Comment by greenpau** [comment]
@lbreitk , forget about the `primary` because yo already have one.

Now, based on your initial config the `reverse_proxy` will be triggered prior to `jwt` plugin and therefore the `jwt` plugin would not be able to intercept a request prior to its reaching `reverse_proxy`. Are we in sync on that point?

**Comment by greenpau** [comment]
> Now I'm getting errors that I apparently I have to have an "allow" rule in my default JWT config, which I don't want - I want all my sites to default to deny access and have a per-site role access.

@lbreitk , what is the error you are getting?

**Comment by greenpau** [comment]
> But without editing my other site configs, it just lets all users in now and doesn't seem to be checking their OpenID roles at all.

@lbreitk , I think it lets user in because of what I mentioned in https://github.com/greenpau/caddy-auth-jwt/issues/71#issuecomment-869979702

**Comment by lbreitk** [comment]
do I just need to switch the lines around in the config then? It worked in the previous version

**Comment by lbreitk** [comment]
@greenpau thanks for being so helpful by the way. I appreciate it. I did try to read all the documentation and readmes BEFORE asking for help.

**Comment by greenpau** [comment]
> I did try to read all the documentation and readmes BEFORE asking for help.

@lbreitk  , all good! 👍 

> do I just need to switch the lines around in the config then? It worked in the previous version

My understanding is that prior `jwt` plugin needs to be mentioned prior to `reverse_proxy`, and that they need to be under the same `route` directive.

```
https://consul.1.example.com https://consul.2.example.com {
  import defaults
  import tls-public
  route {
    jwt {
      allow roles res-consul-access
    }
    reverse_proxy http://consul.service.consul.2.example.com:8500
  }
}
```

The `route` above is the catch all. Basically, everything would end up there.

**Comment by greenpau** [comment]
@lbreitk , also, there is explicit default deny, unless "default allow" is being set.

**Comment by lbreitk** [comment]
> My understanding is that prior jwt plugin needs to be mentioned prior to reverse_proxy, and that they need to be under the same route directive.
I will try this next thank you!

> also, there is explicit default deny, unless "default allow" is being set.
Ah, this is good to know, thanks :)

**Comment by lbreitk** [comment]
@greenpau okay, after all of your help, everything is working, including the original change this thread was for. Thanks so much!

**Comment by greenpau** [comment]
> @greenpau okay, after all of your help, everything is working, including the original change this thread was for. Thanks so much!

@lbreitk , awesome! Great to hear! Please share your usage of Caddy and jwt plugin in a blog post or make a mention of it on social media.
