### ISSUE TITLE
Verison 1.3.1 has a breaking change

### ISSUE THREAD

**Issue by J3m5** [greenpau/caddy-auth-jwt#72]
I just rebuild my docker images and version 1.3.1 was picked.
My config is not working anymore, and there is no warning in the readme or releases page.
The readme has not been updated to reflect the new configuration and there is no upgrade instructions.  

**Configuration**

```
{
	# Debug
	{$DEBUG}
	http_port 8080
	https_port 8443
}

http:// {
	route / {
		jwt {
			primary yes
			option validate_bearer_header
			trusted_public_key {$KID} /etc/caddy/keycloak.pem

			allow roles {$CLIENT_NAME} admin
			allow audience [redacted]
			validate allow_all
			enable claim headers
			disable auth_redirect
		}
	}
}

{$SERVER_NAME} {
	log

	@api {
		not method OPTIONS
		not header Accept *text/html*
		not path /pwa* /_profiler* /docs*
		not header Referer */pwa*
		not header Referer */docs*
		not header Referer */_profiler*
	}

	@pwa {
		path /
		not method OPTIONS
		header Accept *text/html*
	}

	redir @pwa /pwa permanent

	route @api {
		jwt
	}

	route {
		root * {$PROJECT}/public
		push

		# Add links to the API docs and to the Mercure Hub if not set explicitly (e.g. the PWA)
		header ?Link `</docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation", </.well-known/mercure>; rel="mercure"`
		# Disable Google FLOC tracking if not enabled explicitly: https://plausible.io/blog/google-floc
		header ?Permissions-Policy "interest-cohort=()"

		# Comment the following line if you don't want Next.js to catch requests for HTML documents.
		# In this case, they will be handled by the PHP app.
		reverse_proxy /pwa* http://{$PWA_UPSTREAM}

		php_fastcgi unix/{$_HOME}/php/php-fpm.sock

		encode zstd gzip
		file_server
	}
}

```

**Version Information**

1.3.1

**Comment by J3m5** [comment]
I revert back to 1.2.7 and issue is gone.
Error message was about something like the "option" config not existing .
I did not saved the message and downloading the sources take quiet some time.

**Comment by DJFliX** [comment]
Similar issue for me, people using `xcaddy build --with github.com/greenpau/caddy-auth-jwt` are likely to run in to this issue as well unless they update their config or specify the specific version of `caddy-auth-jwt` that should be used. So replacing the command with `xcaddy build --with github.com/greenpau/caddy-auth-jwt@1.2.7`fixed it for me.

**Comment by greenpau** [comment]
@DJFliX , how about migrating the config to the newer versiob?

**Comment by DJFliX** [comment]
> @DJFliX , how about migrating the config to the newer version?

While I agree in theory, I still think that this is a plugin people 'just add' to their xcaddy build and forget about (because so far for me it has been 0 maintenance, which is a good thing). So when the config format changed in a way that makes existing config files fail (no matter how good your intentions were) people will inevitably run in to situations where they need a quick fix. And if the error they get does not tell them "go to github and read the Readme because I made a very good change but it breaks backwards compatibility with your config" that would be fine. But it didn't. So people like me would rather pin an old version than having to deal with breaking changes with cryptic error messages.

**Comment by greenpau** [comment]
> So people like me would rather pin an old version than having to deal with breaking changes with cryptic error messages.

@DJFliX , from my perspective, breaking changes are the way for users to contribute back to a project. I get the inconvenience and all. At the same time, it is a two way street. Also, I could easily squash the entire repo to a single commit 😈

**Comment by greenpau** [comment]
Note for myself, the following two lines:

```
			allow roles {$CLIENT_NAME} admin
			allow audience [redacted]
			validate allow_all
```

would become a rule:

```
acl rule {
  match roles {$CLIENT_NAME} admin
  match audience [redacted]
  allow stop
}
```

The `validate allow_all` is no longer necessary, b/c the default is "all"

The is described in https://github.com/greenpau/caddy-auth-jwt#granting-access-with-access-lists

**Comment by J3m5** [comment]
> from my perspective, breaking changes are the way for users to contribute back to a project.

I don't know from where you get that but it sound wrong.
It could be true at least if the breaking changes would be announced at the release time but that's not the case.

And for having users to contribute back, the best approach IMO is to propose the changes and discuss it with the users before publishing it, and not waiting for the the users services to crash and then having them here complaining about there services crashing because of an unannounced breaking change...

And I read every release messages and changelogs and I saw "Completed plugin rewrite.",
and I was like "wow, great, impressive  and apparently he even did that without a breaking change...",
but I was wrong.
 
I know it's free software and all, you don't owe us anything, but properly announcing this sort of thing would avoid making you waste time (and us too)

Anyway, thanks for the note, and this plugin.
Have a good day.

**Comment by greenpau** [comment]
> I know it's free software and all, you don't owe us anything, but properly announcing this sort of thing would avoid making you waste time (and us too)

@J3m5 , agreed. Should have added a note about.
