### ISSUE TITLE
Parse error: acl directive "default allow" is too long

### ISSUE THREAD

**Issue by optiz0r** [greenpau/caddy-auth-jwt#75]
**Description**

Upgrading my config from v1.2.7 to v1.3.9, the `default allow` option has been changed to `acl default allow` as described in the current Readme, but is no longer parsing, resulting in error `acl directive "default allow" is too long`

**Configuration**

```
whoami.example.com {
  route {
    jwt {
      set auth url https://auth.example.com/auth/oauth2/generic
      # changed from: v1.2.7 syntax
      # default allow
      # changed to: v.1.3.9 syntax
      acl default allow  # line 110
    }
    reverse_proxy * {
      to "http://10.123.123.123:22737"
      transport http {
      }
      # two lines
      # redacted
    }
  }  # line 119: end route
}
```

**Version Information**

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.9
http.handlers.authp v1.4.11
```

**Expected behavior**

Caddy to start up, and accept all requests to whoami vhost

**Actual Behaviour**

Caddy exits 1 with log message:

```
{"level":"info","ts":1624877567.1072474,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
run: adapting config using caddyfile: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:119 - Error during parsing: parsing caddyfile tokens for 'jwt': /etc/caddy/Caddyfile:110 - Error during parsing: acl directive "default allow" is too long
```

**Comment by greenpau** [comment]
@optiz0r , change "acl default allow" to "always allow iss any"

**Comment by greenpau** [comment]
I probably need to readd "acl default allow/deny" back. Will do a quick release.

**Comment by optiz0r** [comment]
The below has done the trick, thanks. The Readme describes the catch-all permit as being `acl default allow`, so if you don't bring this option back (favouring the more explicit rule), then the Readme would need to be updated instead.

```
      acl rule {
        comment Allow all
        always match iss any
        allow
      }
```

**Comment by greenpau** [comment]
@optiz0r , thank you! I am bringing it back. Once again, thank you for reporting! 👍
