### ISSUE TITLE
GitHub authentication

### ISSUE THREAD

**Issue by schu** [greenpau/caddy-auth-jwt#8]
I found this repository via https://github.com/tarent/loginsrv/issues/167

As far as I see, authentication backends and in particular GitHub as backend are not supported (yet?) and caddy-auth-jwt doesn't substitute loginsrv in that regard. Do you plan to add backend support / support for GitHub authentication?

**Comment by greenpau** [comment]
> As far as I see, authentication backends and in particular GitHub as backend are not supported (yet?) and caddy-auth-jwt doesn't substitute loginsrv in that regard. Do you plan to add backend support / support for GitHub authentication?

@schu , thank you for opening this issue! I will try responding to you in a way that I can use the same comment in the plugin documentation later.

The `tarent/loginsrv` combines in it both "authentication" and "authorization" in the same code base.

This repository consists of:
* Caddy v2 Plugin, PLUS
* Exportable functions to issue tokens. Here, it is called "Grantor"

The plugin is "authorization" plugin. It validates tokens present in query parameters, headers, and cookies.

When you protect an endpoint (URL) with the plugin, it does only the above things. It does not perform "authentication." It CAN redirect a user should no tokens are found.

> The auth_url_path is the URL a user gets redirected to when a token is invalid.

Now, what you want is https://github.com/greenpau/caddy-auth-forms plugin. It is "authentication" plugin. Please file an issue in that repo to add support for Github authentication. I would gladly work with you to make it happen.

**Comment by greenpau** [comment]
@schu , please let me know if I answered your question.

**Comment by schu** [comment]
@greenpau thanks, that answers my question.

https://github.com/greenpau/caddy-auth-forms/issues/16
