### ISSUE TITLE
redirect query parameter Commented Out

### ISSUE THREAD

**Issue by dfoster42** [greenpau/caddy-auth-jwt#82]
https://github.com/greenpau/caddy-auth-jwt/blob/42e3bc1519930eb69cca0baab817c372877f0224/caddyfile.go#L309

Is it purposeful that this parameter is commented out and thus not supported?  The readme has documentation on using it.

**Comment by greenpau** [comment]
@dfoster42 , see https://github.com/greenpau/caddy-auth-jwt/pull/81 

I didn't have time to look into it yet. Will let everyone know shortly.

**Comment by greenpau** [comment]
> Is it purposeful that this parameter is commented out and thus not supported?

@dfoster42 , it was commented out by mistake.

**Comment by greenpau** [comment]
@dfoster42 , resolved and released
