### ISSUE TITLE
Failback to HTTP Basic authentication when client doesn't support jwt?

### ISSUE THREAD

**Issue by CaringCat** [greenpau/caddy-auth-jwt#83]
Hi,

I am wondering if it's possible to allow client to use HTTP Basic authentication when it doesn't support jwt?

I have a WebDAV service and would like to utilizes the convenient of caddy-auth sso when using a web browser, however most WebDAV client doesn't support cookies or jwt, and relies on HTTP Basic authentication. Is it possible to config it to work with both situation?

Best wishes.

**Comment by greenpau** [comment]
@CaringCat , i think you might be able to get it working. Do you have a basic config for your caddy instance?

**Comment by CaringCat** [comment]
Thanks, I am currently running with the following Caddyfile:

```
{
    order jwt before file_server
    order authp before jwt
    order webdav after file_server
}

*.example.com {
    @auth host auth.example.com
    handle @auth {
        authp {
            backend local /etc/caddy/auth/user_db.json local
            cookie domain example.com
            cookie lifetime 86400 # 24 hours in seconds
            enable source ip tracking
        }
    }

    @webdav host webdav.example.com
    handle @webdav {
        @get method GET
        jwt {
            primary yes
            set auth url https://auth.example.com
            allow roles authp/user
            validate source address
        }
        file_server @get browse
        webdav
        root * /path/to/webdav
    }

    # Fallback for otherwise unhandled domains
    handle {
        abort
    }
}
```

I figure to achieve my goal, I might need to disable auth redirect, and use ACL to allow anonymous role to continue? However I am too dumb to figure out the ACL part in document.

**Comment by greenpau** [comment]
@CaringCat , try setting the below 

set auth url https://auth.example.com/basic/login/local

this way a user will be redirected to basic auth endpoint.

see if this helps. It is a special endpoint for basic auth for “local” realm.

**Comment by CaringCat** [comment]
> set auth url https://auth.example.com/basic/login/local

It will work for web browsers, however won't work with WebDAV client. 

I have tested on Microsoft-WebDAV-MiniRedir and WinSCP and both failed.

**Comment by greenpau** [comment]
@CaringCat , have you considered matching user agent in a request, i.e. match webdav client user agent strings?

**Comment by CaringCat** [comment]
I was thinking about some kinds of acl and basicauth combination, so for visitpr with authp/user role, go directly to next directives. For visitor with anonymous/guest role, process them to a basicauth directive.

Is this possible to config?

**Comment by greenpau** [comment]
> Is this possible to config?

@CaringCat, I suggest you create a special host to handle webdav clients where you use Caddy's default basicauth. I suggest asking at https://caddy.community/

**Comment by CaringCat** [comment]
Okay, thanks!
